// ─── Speed Tier Data ─────────────────────────────────
// Parsed from Champions OU Speed Tiers (Smogon)
// Missing combos calculated via Gen 8/9 speed formula
// Format: { spe, boost, evs, pokemon[] }

const SPEED_DATA = [
  { spe: 444, boost: 2, evs: "32+", pokemon: ["Mega Aerodactyl","Mega Alakazam"] },
  { spe: 432, boost: 2, evs: "32+", pokemon: ["Mega Beedrill"] },
  { spe: 426, boost: 2, evs: "32+", pokemon: ["Dragapult"] },
  { spe: 426, boost: 2, evs: "32+", pokemon: ["Mega Greninja"] },
  { spe: 410, boost: 2, evs: "32+", pokemon: ["Mega Lopunny","Mega Manectric"] },
  { spe: 408, boost: 2, evs: "32+", pokemon: ["Mega Delphox"] },
  { spe: 404, boost: 2, evs: "32", pokemon: ["Mega Aerodactyl","Mega Alakazam"] },
  { spe: 400, boost: 2, evs: "32+", pokemon: ["Aerodactyl"] },
  { spe: 400, boost: 2, evs: "32+", pokemon: ["Jolteon","Mega Gengar"] },
  { spe: 394, boost: 2, evs: "32", pokemon: ["Mega Beedrill"] },
  { spe: 390, boost: 2, evs: "32+", pokemon: ["Talonflame"] },
  { spe: 388, boost: 2, evs: "32", pokemon: ["Dragapult"] },
  { spe: 388, boost: 2, evs: "32+", pokemon: ["Weavile"] },
  { spe: 388, boost: 2, evs: "32", pokemon: ["Mega Greninja"] },
  { spe: 386, boost: 2, evs: "32+", pokemon: ["Mega Meowstic"] },
  { spe: 384, boost: 2, evs: "32+", pokemon: ["Meowscarada","Noivern"] },
  { spe: 382, boost: 2, evs: "32+", pokemon: ["Greninja"] },
  { spe: 380, boost: 2, evs: "32+", pokemon: ["Mega Pidgeot"] },
  { spe: 378, boost: 2, evs: "32+", pokemon: ["Mega Starmie","Sneasler"] },
  { spe: 378, boost: 2, evs: "32+", pokemon: ["Alakazam","Mega Froslass"] },
  { spe: 374, boost: 2, evs: "32+", pokemon: ["Hawlucha"] },
  { spe: 374, boost: 2, evs: "32", pokemon: ["Mega Lopunny","Mega Manectric"] },
  { spe: 374, boost: 2, evs: "32+", pokemon: ["Mega Hawlucha"] },
  { spe: 372, boost: 2, evs: "32", pokemon: ["Mega Delphox"] },
  { spe: 370, boost: 2, evs: "32+", pokemon: ["Salazzle"] },
  { spe: 368, boost: 2, evs: "32+", pokemon: ["Whimsicott"] },
  { spe: 366, boost: 2, evs: "32+", pokemon: ["Starmie","Mega Absol","Mega Houndoom"] },
  { spe: 364, boost: 2, evs: "32", pokemon: ["Aerodactyl"] },
  { spe: 364, boost: 2, evs: "32", pokemon: ["Jolteon","Mega Gengar"] },
  { spe: 362, boost: 2, evs: "32+", pokemon: ["Serperior"] },
  { spe: 360, boost: 2, evs: "32+", pokemon: ["Lycanroc-Midday","Mega Lucario"] },
  { spe: 358, boost: 2, evs: "32+", pokemon: ["Maushold"] },
  { spe: 356, boost: 2, evs: "32+", pokemon: ["Mega Gallade","Mega Skarmory"] },
  { spe: 356, boost: 2, evs: "32+", pokemon: ["Gengar","Lycanroc-Dusk","Hisuian Zoroark","Alolan Raichu","Espeon","Froslass","Raichu","Tauros"] },
  { spe: 356, boost: 2, evs: "32", pokemon: ["Talonflame"] },
  { spe: 354, boost: 2, evs: "32", pokemon: ["Weavile"] },
  { spe: 354, boost: 2, evs: "32+", pokemon: ["Heliolisk","Alolan Ninetales"] },
  { spe: 352, boost: 2, evs: "32", pokemon: ["Mega Meowstic"] },
  { spe: 352, boost: 2, evs: "32+", pokemon: ["Infernape"] },
  { spe: 350, boost: 2, evs: "32", pokemon: ["Meowscarada","Noivern"] },
  { spe: 348, boost: 2, evs: "32", pokemon: ["Greninja"] },
  { spe: 346, boost: 2, evs: "32", pokemon: ["Mega Pidgeot"] },
  { spe: 344, boost: 2, evs: "32", pokemon: ["Mega Starmie","Sneasler"] },
  { spe: 344, boost: 2, evs: "32+", pokemon: ["Espathra"] },
  { spe: 344, boost: 2, evs: "32+", pokemon: ["Zoroark","Lopunny","Manectric","Mega Pinsir","Mega Sharpedo"] },
  { spe: 344, boost: 2, evs: "32", pokemon: ["Alakazam","Mega Froslass"] },
  { spe: 342, boost: 2, evs: "32+", pokemon: ["Delphox","Meowstic"] },
  { spe: 340, boost: 2, evs: "32", pokemon: ["Hawlucha"] },
  { spe: 340, boost: 2, evs: "0", pokemon: ["Mega Aerodactyl","Mega Alakazam"] },
  { spe: 340, boost: 2, evs: "32+", pokemon: ["Mega Excadrill"] },
  { spe: 340, boost: 2, evs: "32", pokemon: ["Mega Hawlucha"] },
  { spe: 338, boost: 2, evs: "32+", pokemon: ["Garchomp","Mega Floette"] },
  { spe: 338, boost: 2, evs: "32", pokemon: ["Salazzle"] },
  { spe: 336, boost: 2, evs: "32+", pokemon: ["Mega Glimmora"] },
  { spe: 336, boost: 2, evs: "32", pokemon: ["Whimsicott"] },
  { spe: 336, boost: 2, evs: "32+", pokemon: ["Pidgeot"] },
  { spe: 334, boost: 2, evs: "32+", pokemon: ["Mega Charizard X","Mega Dragonite","Mega Gardevoir","Mega Medicham","Volcarona"] },
  { spe: 334, boost: 2, evs: "32", pokemon: ["Starmie","Mega Absol","Mega Houndoom"] },
  { spe: 334, boost: 2, evs: "32+", pokemon: ["Paldean Tauros","Typhlosion","Charizard","Mega Charizard Y","Mega Glalie","Mega Kangaskhan","Ninetales","Palafin"] },
  { spe: 333, boost: 1, evs: "32+", pokemon: ["Mega Aerodactyl"] },
  { spe: 333, boost: 1, evs: "32+", pokemon: ["Mega Alakazam"] },
  { spe: 332, boost: 2, evs: "32+", pokemon: ["Gourgeist-Small"] },
  { spe: 330, boost: 2, evs: "32", pokemon: ["Serperior"] },
  { spe: 330, boost: 2, evs: "32+", pokemon: ["Hydreigon"] },
  { spe: 330, boost: 2, evs: "0", pokemon: ["Mega Beedrill"] },
  { spe: 328, boost: 2, evs: "32", pokemon: ["Lycanroc-Midday","Mega Lucario"] },
  { spe: 326, boost: 2, evs: "32", pokemon: ["Maushold"] },
  { spe: 326, boost: 2, evs: "32+", pokemon: ["Morpeko"] },
  { spe: 324, boost: 2, evs: "0", pokemon: ["Dragapult"] },
  { spe: 324, boost: 2, evs: "32", pokemon: ["Mega Gallade","Mega Skarmory"] },
  { spe: 324, boost: 2, evs: "32", pokemon: ["Gengar","Lycanroc-Dusk","Hisuian Zoroark","Alolan Raichu","Espeon","Froslass","Raichu","Tauros"] },
  { spe: 324, boost: 2, evs: "0", pokemon: ["Mega Greninja"] },
  { spe: 324, boost: 2, evs: "32+", pokemon: ["Mimikyu"] },
  { spe: 324, boost: 1, evs: "32+", pokemon: ["Mega Beedrill"] },
  { spe: 322, boost: 2, evs: "32+", pokemon: ["Gliscor"] },
  { spe: 322, boost: 2, evs: "32", pokemon: ["Heliolisk","Alolan Ninetales"] },
  { spe: 322, boost: 2, evs: "32+", pokemon: ["Hisuian Typhlosion","Arcanine","Houndoom","Sharpedo"] },
  { spe: 320, boost: 2, evs: "32", pokemon: ["Infernape"] },
  { spe: 320, boost: 2, evs: "32+", pokemon: ["Tinkaton"] },
  { spe: 319, boost: 1, evs: "32+", pokemon: ["Dragapult"] },
  { spe: 319, boost: 1, evs: "32+", pokemon: ["Mega Greninja"] },
  { spe: 316, boost: 2, evs: "32+", pokemon: ["Krookodile","Mega Garchomp"] },
  { spe: 314, boost: 2, evs: "32", pokemon: ["Espathra"] },
  { spe: 314, boost: 2, evs: "32", pokemon: ["Zoroark","Lopunny","Manectric","Mega Pinsir","Mega Sharpedo"] },
  { spe: 312, boost: 2, evs: "32+", pokemon: ["Lucario"] },
  { spe: 312, boost: 2, evs: "32+", pokemon: ["Hisuian Arcanine","Kangaskhan","Mega Chandelure","Pikachu","Roserade"] },
  { spe: 312, boost: 2, evs: "32", pokemon: ["Delphox","Meowstic"] },
  { spe: 310, boost: 2, evs: "32", pokemon: ["Mega Excadrill"] },
  { spe: 310, boost: 2, evs: "0", pokemon: ["Mega Lopunny","Mega Manectric"] },
  { spe: 308, boost: 2, evs: "32+", pokemon: ["Excadrill"] },
  { spe: 308, boost: 2, evs: "32", pokemon: ["Garchomp","Mega Floette"] },
  { spe: 308, boost: 2, evs: "0", pokemon: ["Mega Delphox"] },
  { spe: 307, boost: 1, evs: "32+", pokemon: ["Mega Lopunny","Mega Manectric"] },
  { spe: 306, boost: 2, evs: "32", pokemon: ["Mega Glimmora"] },
  { spe: 306, boost: 2, evs: "0-", pokemon: ["Mega Aerodactyl","Mega Alakazam"] },
  { spe: 306, boost: 2, evs: "32", pokemon: ["Pidgeot"] },
  { spe: 306, boost: 1, evs: "32+", pokemon: ["Mega Delphox"] },
  { spe: 304, boost: 2, evs: "32", pokemon: ["Mega Charizard X","Mega Dragonite"] },
  { spe: 304, boost: 2, evs: "32", pokemon: ["Mega Gardevoir","Mega Medicham","Volcarona"] },
  { spe: 304, boost: 2, evs: "32", pokemon: ["Paldean Tauros","Typhlosion","Charizard","Mega Charizard Y","Mega Glalie","Mega Kangaskhan","Ninetales","Palafin"] },
  { spe: 303, boost: 1, evs: "32", pokemon: ["Mega Aerodactyl"] },
  { spe: 303, boost: 1, evs: "32", pokemon: ["Mega Alakazam"] },
  { spe: 302, boost: 2, evs: "32+", pokemon: ["Glimmora"] },
  { spe: 302, boost: 2, evs: "32+", pokemon: ["Rotom-Wash"] },
  { spe: 302, boost: 2, evs: "32", pokemon: ["Gourgeist-Small"] },
  { spe: 300, boost: 2, evs: "32+", pokemon: ["Ceruledge","Kommo-o","Quaquaval"] },
  { spe: 300, boost: 2, evs: "0", pokemon: ["Aerodactyl"] },
  { spe: 300, boost: 2, evs: "32", pokemon: ["Hydreigon"] },
  { spe: 300, boost: 2, evs: "32+", pokemon: ["Heracross","Hisuian Samurott","Archaludon","Kleavor","Pinsir"] },
  { spe: 300, boost: 2, evs: "0", pokemon: ["Jolteon","Mega Gengar"] },
  { spe: 300, boost: 1, evs: "32+", pokemon: ["Aerodactyl"] },
  { spe: 300, boost: 1, evs: "32+", pokemon: ["Jolteon","Mega Gengar"] },
  { spe: 298, boost: 2, evs: "32", pokemon: ["Morpeko"] },
  { spe: 298, boost: 2, evs: "32+", pokemon: ["Gourgeist"] },
  { spe: 296, boost: 2, evs: "0-", pokemon: ["Mega Beedrill"] },
  { spe: 296, boost: 2, evs: "32", pokemon: ["Mimikyu"] },
  { spe: 295, boost: 1, evs: "32", pokemon: ["Mega Beedrill"] },
  { spe: 294, boost: 2, evs: "32", pokemon: ["Gliscor"] },
  { spe: 294, boost: 2, evs: "32", pokemon: ["Hisuian Typhlosion","Arcanine","Houndoom","Sharpedo"] },
  { spe: 292, boost: 2, evs: "32+", pokemon: ["Gyarados","Mega Gyarados"] },
  { spe: 292, boost: 2, evs: "0", pokemon: ["Talonflame"] },
  { spe: 292, boost: 2, evs: "32", pokemon: ["Tinkaton"] },
  { spe: 292, boost: 2, evs: "32+", pokemon: ["Milotic"] },
  { spe: 292, boost: 1, evs: "32+", pokemon: ["Talonflame"] },
  { spe: 291, boost: 1, evs: "32", pokemon: ["Dragapult"] },
  { spe: 291, boost: 1, evs: "32+", pokemon: ["Weavile"] },
  { spe: 291, boost: 1, evs: "32", pokemon: ["Mega Greninja"] },
  { spe: 290, boost: 2, evs: "32+", pokemon: ["Dragonite","Gallade","Gardevoir","Mega Altaria","Venusaur"] },
  { spe: 290, boost: 2, evs: "0-", pokemon: ["Dragapult"] },
  { spe: 290, boost: 2, evs: "0", pokemon: ["Weavile"] },
  { spe: 290, boost: 2, evs: "32+", pokemon: ["Mamoswine","Medicham","Chandelure","Glalie","Goodra","Mega Meganium","Mega Venusaur","Meganium"] },
  { spe: 290, boost: 2, evs: "0-", pokemon: ["Mega Greninja"] },
  { spe: 289, boost: 1, evs: "32+", pokemon: ["Mega Meowstic"] },
  { spe: 288, boost: 2, evs: "0", pokemon: ["Mega Meowstic"] },
  { spe: 288, boost: 2, evs: "32+", pokemon: ["Vanilluxe"] },
  { spe: 288, boost: 2, evs: "32", pokemon: ["Krookodile","Mega Garchomp"] },
  { spe: 288, boost: 1, evs: "32+", pokemon: ["Meowscarada"] },
  { spe: 288, boost: 1, evs: "32+", pokemon: ["Noivern"] },
  { spe: 286, boost: 2, evs: "32+", pokemon: ["Basculegion","Blastoise","Diggersby","Feraligatr","Mega Blastoise","Mega Feraligatr"] },
  { spe: 286, boost: 2, evs: "0", pokemon: ["Meowscarada","Noivern"] },
  { spe: 286, boost: 1, evs: "32+", pokemon: ["Greninja"] },
  { spe: 285, boost: 1, evs: "32+", pokemon: ["Mega Pidgeot"] },
  { spe: 284, boost: 2, evs: "32", pokemon: ["Lucario"] },
  { spe: 284, boost: 2, evs: "0", pokemon: ["Greninja"] },
  { spe: 284, boost: 2, evs: "32", pokemon: ["Hisuian Arcanine","Kangaskhan","Mega Chandelure","Pikachu","Roserade"] },
  { spe: 283, boost: 1, evs: "32+", pokemon: ["Mega Starmie","Sneasler"] },
  { spe: 283, boost: 1, evs: "32+", pokemon: ["Alakazam","Mega Froslass"] },
  { spe: 282, boost: 2, evs: "0", pokemon: ["Mega Pidgeot"] },
  { spe: 280, boost: 2, evs: "0", pokemon: ["Mega Starmie","Sneasler"] },
  { spe: 280, boost: 2, evs: "32", pokemon: ["Excadrill"] },
  { spe: 280, boost: 2, evs: "0", pokemon: ["Alakazam","Mega Froslass"] },
  { spe: 280, boost: 1, evs: "32+", pokemon: ["Hawlucha"] },
  { spe: 280, boost: 1, evs: "32", pokemon: ["Mega Lopunny","Mega Manectric"] },
  { spe: 280, boost: 1, evs: "32+", pokemon: ["Mega Hawlucha"] },
  { spe: 279, boost: 1, evs: "32", pokemon: ["Mega Delphox"] },
  { spe: 278, boost: 2, evs: "32+", pokemon: ["Armarouge"] },
  { spe: 278, boost: 2, evs: "32+", pokemon: ["Absol","Mega Heracross","Florges","Garbodor","Klefki","Mega Banette","Mega Emboar","Mega Scizor","Mega Scovillain","Scovillain"] },
  { spe: 278, boost: 2, evs: "0-", pokemon: ["Mega Lopunny","Mega Manectric"] },
  { spe: 277, boost: 1, evs: "32+", pokemon: ["Salazzle"] },
  { spe: 276, boost: 2, evs: "0", pokemon: ["Hawlucha"] },
  { spe: 276, boost: 2, evs: "32", pokemon: ["Glimmora"] },
  { spe: 276, boost: 2, evs: "32", pokemon: ["Rotom-Wash"] },
  { spe: 276, boost: 2, evs: "0-", pokemon: ["Mega Delphox"] },
  { spe: 276, boost: 2, evs: "0", pokemon: ["Mega Hawlucha"] },
  { spe: 276, boost: 1, evs: "32+", pokemon: ["Whimsicott"] },
  { spe: 274, boost: 2, evs: "32", pokemon: ["Ceruledge","Kommo-o","Quaquaval"] },
  { spe: 274, boost: 2, evs: "32", pokemon: ["Heracross","Hisuian Samurott","Archaludon","Kleavor","Pinsir"] },
  { spe: 274, boost: 2, evs: "0", pokemon: ["Salazzle"] },
  { spe: 274, boost: 1, evs: "32+", pokemon: ["Starmie"] },
  { spe: 274, boost: 1, evs: "32+", pokemon: ["Mega Absol","Mega Houndoom"] },
  { spe: 273, boost: 1, evs: "32", pokemon: ["Aerodactyl"] },
  { spe: 273, boost: 1, evs: "32", pokemon: ["Jolteon","Mega Gengar"] },
  { spe: 272, boost: 2, evs: "0", pokemon: ["Whimsicott"] },
  { spe: 272, boost: 2, evs: "32", pokemon: ["Gourgeist"] },
  { spe: 272, boost: 2, evs: "32+", pokemon: ["Slurpuff","Tsareena"] },
  { spe: 271, boost: 1, evs: "32+", pokemon: ["Serperior"] },
  { spe: 270, boost: 2, evs: "32+", pokemon: ["Mega Tyranitar","Tyrantrum"] },
  { spe: 270, boost: 2, evs: "0-", pokemon: ["Aerodactyl"] },
  { spe: 270, boost: 2, evs: "0", pokemon: ["Starmie","Mega Absol","Mega Houndoom"] },
  { spe: 270, boost: 2, evs: "0-", pokemon: ["Jolteon","Mega Gengar"] },
  { spe: 270, boost: 2, evs: "32+", pokemon: ["Sandaconda"] },
  { spe: 270, boost: 1, evs: "32+", pokemon: ["Lycanroc-Midday","Mega Lucario"] },
  { spe: 268, boost: 2, evs: "32+", pokemon: ["Flapple","Skarmory","Victreebel"] },
  { spe: 268, boost: 2, evs: "32+", pokemon: ["Decidueye","Mega Clefable","Mega Victreebel","Mr. Rime","Politoed","Polteageist"] },
  { spe: 268, boost: 1, evs: "32+", pokemon: ["Maushold"] },
  { spe: 267, boost: 1, evs: "32+", pokemon: ["Gengar","Lycanroc-Dusk","Hisuian Zoroark"] },
  { spe: 267, boost: 1, evs: "32+", pokemon: ["Mega Gallade","Mega Skarmory"] },
  { spe: 267, boost: 1, evs: "32", pokemon: ["Talonflame"] },
  { spe: 267, boost: 1, evs: "32+", pokemon: ["Alolan Raichu","Espeon","Froslass","Raichu","Tauros"] },
  { spe: 266, boost: 2, evs: "32", pokemon: ["Mega Gyarados"] },
  { spe: 266, boost: 2, evs: "32", pokemon: ["Gyarados"] },
  { spe: 266, boost: 2, evs: "0", pokemon: ["Serperior"] },
  { spe: 266, boost: 2, evs: "32", pokemon: ["Milotic"] },
  { spe: 266, boost: 2, evs: "32+", pokemon: ["Gourgeist-Large"] },
  { spe: 265, boost: 1, evs: "32", pokemon: ["Weavile"] },
  { spe: 265, boost: 1, evs: "32+", pokemon: ["Heliolisk"] },
  { spe: 265, boost: 1, evs: "32+", pokemon: ["Alolan Ninetales"] },
  { spe: 264, boost: 2, evs: "32", pokemon: ["Dragonite","Mega Altaria","Venusaur"] },
  { spe: 264, boost: 2, evs: "0", pokemon: ["Lycanroc-Midday","Mega Lucario"] },
  { spe: 264, boost: 2, evs: "32", pokemon: ["Gallade","Gardevoir"] },
  { spe: 264, boost: 2, evs: "32", pokemon: ["Mamoswine","Medicham","Chandelure","Glalie","Goodra","Mega Meganium","Mega Venusaur","Meganium"] },
  { spe: 264, boost: 1, evs: "32+", pokemon: ["Infernape"] },
  { spe: 264, boost: 1, evs: "32", pokemon: ["Mega Meowstic"] },
  { spe: 262, boost: 2, evs: "0", pokemon: ["Maushold"] },
  { spe: 262, boost: 2, evs: "32", pokemon: ["Vanilluxe"] },
  { spe: 262, boost: 2, evs: "0-", pokemon: ["Talonflame"] },
  { spe: 262, boost: 1, evs: "32", pokemon: ["Meowscarada"] },
  { spe: 262, boost: 1, evs: "32", pokemon: ["Noivern"] },
  { spe: 261, boost: 1, evs: "32", pokemon: ["Greninja"] },
  { spe: 260, boost: 2, evs: "32", pokemon: ["Basculegion","Blastoise","Diggersby","Feraligatr","Mega Blastoise","Mega Feraligatr"] },
  { spe: 260, boost: 2, evs: "0", pokemon: ["Mega Gallade","Mega Skarmory"] },
  { spe: 260, boost: 2, evs: "0-", pokemon: ["Weavile"] },
  { spe: 260, boost: 2, evs: "0", pokemon: ["Gengar","Lycanroc-Dusk","Hisuian Zoroark","Alolan Raichu","Espeon","Froslass","Raichu","Tauros"] },
  { spe: 260, boost: 2, evs: "32+", pokemon: ["Corviknight"] },
  { spe: 259, boost: 1, evs: "32", pokemon: ["Mega Pidgeot"] },
  { spe: 258, boost: 2, evs: "0-", pokemon: ["Mega Meowstic"] },
  { spe: 258, boost: 2, evs: "0", pokemon: ["Heliolisk","Alolan Ninetales"] },
  { spe: 258, boost: 2, evs: "32+", pokemon: ["Skeledirge"] },
  { spe: 258, boost: 1, evs: "32", pokemon: ["Mega Starmie","Sneasler"] },
  { spe: 258, boost: 1, evs: "32+", pokemon: ["Espathra","Zoroark"] },
  { spe: 258, boost: 1, evs: "32", pokemon: ["Alakazam","Mega Froslass"] },
  { spe: 258, boost: 1, evs: "32+", pokemon: ["Lopunny","Manectric","Mega Pinsir","Mega Sharpedo"] },
  { spe: 256, boost: 2, evs: "0-", pokemon: ["Meowscarada","Noivern"] },
  { spe: 256, boost: 2, evs: "0", pokemon: ["Infernape"] },
  { spe: 256, boost: 2, evs: "32+", pokemon: ["Scizor","Banette","Chimecho","Emboar","Mega Chimecho","Orthworm","Pelipper","Umbreon","Vaporeon"] },
  { spe: 256, boost: 1, evs: "32+", pokemon: ["Delphox","Meowstic"] },
  { spe: 255, boost: 1, evs: "32+", pokemon: ["Mega Excadrill"] },
  { spe: 255, boost: 1, evs: "0", pokemon: ["Mega Aerodactyl"] },
  { spe: 255, boost: 1, evs: "32", pokemon: ["Hawlucha"] },
  { spe: 255, boost: 1, evs: "0", pokemon: ["Mega Alakazam"] },
  { spe: 255, boost: 1, evs: "32", pokemon: ["Mega Hawlucha"] },
  { spe: 254, boost: 2, evs: "32", pokemon: ["Armarouge"] },
  { spe: 254, boost: 2, evs: "0-", pokemon: ["Greninja"] },
  { spe: 254, boost: 2, evs: "32", pokemon: ["Absol","Mega Heracross","Florges","Garbodor","Klefki","Mega Banette","Mega Emboar","Mega Scizor","Mega Scovillain","Scovillain"] },
  { spe: 254, boost: 2, evs: "32+", pokemon: ["Chesnaught"] },
  { spe: 253, boost: 1, evs: "32+", pokemon: ["Garchomp"] },
  { spe: 253, boost: 1, evs: "32", pokemon: ["Salazzle"] },
  { spe: 253, boost: 1, evs: "32+", pokemon: ["Mega Floette"] },
  { spe: 252, boost: 2, evs: "0-", pokemon: ["Mega Starmie","Sneasler"] },
  { spe: 252, boost: 2, evs: "0-", pokemon: ["Mega Pidgeot","Alakazam","Mega Froslass"] },
  { spe: 252, boost: 1, evs: "32+", pokemon: ["Mega Glimmora"] },
  { spe: 252, boost: 1, evs: "32", pokemon: ["Whimsicott"] },
  { spe: 252, boost: 1, evs: "32+", pokemon: ["Pidgeot"] },
  { spe: 250, boost: 2, evs: "0", pokemon: ["Espathra"] },
  { spe: 250, boost: 2, evs: "0", pokemon: ["Zoroark","Lopunny","Manectric","Mega Pinsir","Mega Sharpedo"] },
  { spe: 250, boost: 1, evs: "32+", pokemon: ["Mega Charizard X","Mega Dragonite","Mega Medicham","Paldean Tauros","Typhlosion","Volcarona"] },
  { spe: 250, boost: 1, evs: "32", pokemon: ["Starmie"] },
  { spe: 250, boost: 1, evs: "32+", pokemon: ["Mega Gardevoir"] },
  { spe: 250, boost: 1, evs: "32", pokemon: ["Mega Absol","Mega Houndoom"] },
  { spe: 250, boost: 1, evs: "32+", pokemon: ["Charizard","Mega Charizard Y","Mega Glalie","Mega Kangaskhan","Ninetales","Palafin"] },
  { spe: 249, boost: 1, evs: "32+", pokemon: ["Gourgeist-Small"] },
  { spe: 248, boost: 2, evs: "0-", pokemon: ["Hawlucha"] },
  { spe: 248, boost: 2, evs: "0-", pokemon: ["Mega Hawlucha"] },
  { spe: 248, boost: 2, evs: "0", pokemon: ["Delphox","Meowstic"] },
  { spe: 248, boost: 2, evs: "32", pokemon: ["Slurpuff","Tsareena"] },
  { spe: 248, boost: 2, evs: "32+", pokemon: ["Tyranitar"] },
  { spe: 247, boost: 1, evs: "32+", pokemon: ["Hydreigon"] },
  { spe: 247, boost: 1, evs: "32", pokemon: ["Serperior"] },
  { spe: 247, boost: 1, evs: "0", pokemon: ["Mega Beedrill"] },
  { spe: 246, boost: 2, evs: "32", pokemon: ["Mega Tyranitar","Tyrantrum"] },
  { spe: 246, boost: 2, evs: "32+", pokemon: ["Aegislash"] },
  { spe: 246, boost: 2, evs: "0", pokemon: ["Mega Excadrill"] },
  { spe: 246, boost: 2, evs: "0-", pokemon: ["Salazzle"] },
  { spe: 246, boost: 2, evs: "32", pokemon: ["Sandaconda"] },
  { spe: 246, boost: 2, evs: "32+", pokemon: ["Abomasnow","Clefable","Empoleon","Hisuian Decidueye","Hisuian Goodra","Incineroar","Primarina","Sylveon"] },
  { spe: 246, boost: 1, evs: "32", pokemon: ["Lycanroc-Midday","Mega Lucario"] },
  { spe: 244, boost: 2, evs: "32", pokemon: ["Skarmory","Victreebel"] },
  { spe: 244, boost: 2, evs: "32", pokemon: ["Flapple"] },
  { spe: 244, boost: 2, evs: "0", pokemon: ["Garchomp","Mega Floette"] },
  { spe: 244, boost: 2, evs: "0-", pokemon: ["Whimsicott"] },
  { spe: 244, boost: 2, evs: "32", pokemon: ["Decidueye","Mega Clefable","Mega Victreebel","Mr. Rime","Politoed","Polteageist"] },
  { spe: 244, boost: 1, evs: "32", pokemon: ["Maushold"] },
  { spe: 244, boost: 1, evs: "32+", pokemon: ["Morpeko"] },
  { spe: 243, boost: 1, evs: "0", pokemon: ["Dragapult"] },
  { spe: 243, boost: 1, evs: "32", pokemon: ["Gengar","Lycanroc-Dusk","Hisuian Zoroark"] },
  { spe: 243, boost: 1, evs: "32", pokemon: ["Mega Gallade","Mega Skarmory"] },
  { spe: 243, boost: 1, evs: "0", pokemon: ["Mega Greninja"] },
  { spe: 243, boost: 1, evs: "32", pokemon: ["Alolan Raichu","Espeon","Froslass","Raichu","Tauros"] },
  { spe: 243, boost: 1, evs: "32+", pokemon: ["Mimikyu"] },
  { spe: 242, boost: 2, evs: "0", pokemon: ["Mega Glimmora"] },
  { spe: 242, boost: 2, evs: "0-", pokemon: ["Starmie","Mega Absol","Mega Houndoom"] },
  { spe: 242, boost: 2, evs: "0", pokemon: ["Pidgeot"] },
  { spe: 242, boost: 2, evs: "32", pokemon: ["Gourgeist-Large"] },
  { spe: 242, boost: 2, evs: "32+", pokemon: ["Aurorus","Pangoro"] },
  { spe: 241, boost: 1, evs: "32+", pokemon: ["Gliscor","Hisuian Typhlosion"] },
  { spe: 241, boost: 1, evs: "32", pokemon: ["Heliolisk"] },
  { spe: 241, boost: 1, evs: "32", pokemon: ["Alolan Ninetales"] },
  { spe: 241, boost: 1, evs: "32+", pokemon: ["Arcanine","Houndoom","Sharpedo"] },
  { spe: 240, boost: 2, evs: "0", pokemon: ["Mega Charizard X","Mega Dragonite","Mega Gardevoir","Mega Medicham","Volcarona"] },
  { spe: 240, boost: 2, evs: "0", pokemon: ["Paldean Tauros","Typhlosion","Charizard","Mega Charizard Y","Mega Glalie","Mega Kangaskhan","Ninetales","Palafin"] },
  { spe: 240, boost: 1, evs: "32", pokemon: ["Infernape"] },
  { spe: 240, boost: 1, evs: "32+", pokemon: ["Tinkaton"] },
  { spe: 238, boost: 2, evs: "0-", pokemon: ["Serperior"] },
  { spe: 238, boost: 2, evs: "0", pokemon: ["Gourgeist-Small"] },
  { spe: 238, boost: 2, evs: "32", pokemon: ["Corviknight"] },
  { spe: 237, boost: 1, evs: "32+", pokemon: ["Krookodile","Mega Garchomp"] },
  { spe: 236, boost: 2, evs: "32+", pokemon: ["Torterra"] },
  { spe: 236, boost: 2, evs: "0-", pokemon: ["Lycanroc-Midday","Mega Lucario"] },
  { spe: 236, boost: 2, evs: "0", pokemon: ["Hydreigon"] },
  { spe: 236, boost: 2, evs: "32", pokemon: ["Skeledirge"] },
  { spe: 236, boost: 2, evs: "32+", pokemon: ["Trevenant"] },
  { spe: 235, boost: 1, evs: "32", pokemon: ["Espathra","Zoroark"] },
  { spe: 235, boost: 1, evs: "32", pokemon: ["Lopunny","Manectric","Mega Pinsir","Mega Sharpedo"] },
  { spe: 234, boost: 2, evs: "0-", pokemon: ["Mega Gallade","Mega Skarmory"] },
  { spe: 234, boost: 2, evs: "0-", pokemon: ["Maushold","Gengar","Lycanroc-Dusk","Hisuian Zoroark","Alolan Raichu","Espeon","Froslass","Raichu","Tauros"] },
  { spe: 234, boost: 2, evs: "32", pokemon: ["Scizor","Banette","Chimecho","Emboar","Mega Chimecho","Orthworm","Pelipper","Umbreon","Vaporeon"] },
  { spe: 234, boost: 2, evs: "0", pokemon: ["Morpeko"] },
  { spe: 234, boost: 2, evs: "32+", pokemon: ["Ampharos","Golurk","Machamp","Mega Golurk"] },
  { spe: 234, boost: 1, evs: "32+", pokemon: ["Hisuian Arcanine","Lucario"] },
  { spe: 234, boost: 1, evs: "32", pokemon: ["Delphox","Meowstic"] },
  { spe: 234, boost: 1, evs: "32+", pokemon: ["Kangaskhan","Mega Chandelure","Pikachu","Roserade"] },
  { spe: 232, boost: 2, evs: "0-", pokemon: ["Heliolisk","Alolan Ninetales"] },
  { spe: 232, boost: 2, evs: "0", pokemon: ["Mimikyu"] },
  { spe: 232, boost: 2, evs: "32", pokemon: ["Chesnaught"] },
  { spe: 232, boost: 2, evs: "32+", pokemon: ["Gourgeist-Super"] },
  { spe: 232, boost: 1, evs: "32", pokemon: ["Mega Excadrill"] },
  { spe: 232, boost: 1, evs: "0", pokemon: ["Mega Lopunny","Mega Manectric"] },
  { spe: 231, boost: 1, evs: "32+", pokemon: ["Excadrill"] },
  { spe: 231, boost: 1, evs: "32", pokemon: ["Garchomp"] },
  { spe: 231, boost: 1, evs: "0", pokemon: ["Mega Delphox"] },
  { spe: 231, boost: 1, evs: "32", pokemon: ["Mega Floette"] },
  { spe: 230, boost: 2, evs: "0", pokemon: ["Gliscor"] },
  { spe: 230, boost: 2, evs: "0-", pokemon: ["Infernape"] },
  { spe: 230, boost: 2, evs: "0", pokemon: ["Hisuian Typhlosion","Arcanine","Houndoom","Sharpedo"] },
  { spe: 229, boost: 1, evs: "32", pokemon: ["Mega Glimmora"] },
  { spe: 229, boost: 1, evs: "0-", pokemon: ["Mega Aerodactyl"] },
  { spe: 229, boost: 1, evs: "0-", pokemon: ["Mega Alakazam"] },
  { spe: 229, boost: 1, evs: "32", pokemon: ["Pidgeot"] },
  { spe: 228, boost: 2, evs: "0", pokemon: ["Tinkaton"] },
  { spe: 228, boost: 1, evs: "32", pokemon: ["Mega Charizard X","Mega Dragonite"] },
  { spe: 228, boost: 1, evs: "32", pokemon: ["Mega Medicham","Volcarona","Paldean Tauros","Typhlosion"] },
  { spe: 228, boost: 1, evs: "32", pokemon: ["Mega Gardevoir"] },
  { spe: 228, boost: 1, evs: "32", pokemon: ["Charizard","Mega Charizard Y","Mega Glalie","Mega Kangaskhan","Ninetales","Palafin"] },
  { spe: 226, boost: 2, evs: "32", pokemon: ["Tyranitar"] },
  { spe: 226, boost: 1, evs: "32+", pokemon: ["Rotom-Wash","Glimmora"] },
  { spe: 226, boost: 1, evs: "32", pokemon: ["Gourgeist-Small"] },
  { spe: 225, boost: 1, evs: "32+", pokemon: ["Heracross","Hisuian Samurott","Kommo-o","Quaquaval"] },
  { spe: 225, boost: 1, evs: "0", pokemon: ["Aerodactyl"] },
  { spe: 225, boost: 1, evs: "32", pokemon: ["Hydreigon"] },
  { spe: 225, boost: 1, evs: "32+", pokemon: ["Ceruledge"] },
  { spe: 225, boost: 1, evs: "0", pokemon: ["Jolteon","Mega Gengar"] },
  { spe: 225, boost: 1, evs: "32+", pokemon: ["Archaludon","Kleavor","Pinsir"] },
  { spe: 224, boost: 2, evs: "32", pokemon: ["Aegislash"] },
  { spe: 224, boost: 2, evs: "0-", pokemon: ["Espathra"] },
  { spe: 224, boost: 2, evs: "0-", pokemon: ["Zoroark","Lopunny","Manectric","Mega Pinsir","Mega Sharpedo"] },
  { spe: 224, boost: 2, evs: "0", pokemon: ["Krookodile","Mega Garchomp"] },
  { spe: 224, boost: 2, evs: "32", pokemon: ["Abomasnow","Clefable","Empoleon","Hisuian Decidueye","Hisuian Goodra","Incineroar","Primarina","Sylveon"] },
  { spe: 224, boost: 2, evs: "32+", pokemon: ["Audino","Azumarill","Beartic","Kingambit","Mega Aggron","Mega Audino","Sableye","Sinistcha"] },
  { spe: 223, boost: 1, evs: "32", pokemon: ["Morpeko"] },
  { spe: 223, boost: 1, evs: "32+", pokemon: ["Gourgeist"] },
  { spe: 222, boost: 2, evs: "0-", pokemon: ["Delphox","Meowstic"] },
  { spe: 222, boost: 1, evs: "0-", pokemon: ["Mega Beedrill"] },
  { spe: 222, boost: 1, evs: "32", pokemon: ["Mimikyu"] },
  { spe: 222, boost: 0, evs: "32+", pokemon: ["Mega Aerodactyl","Mega Alakazam"] },
  { spe: 220, boost: 2, evs: "0", pokemon: ["Lucario"] },
  { spe: 220, boost: 2, evs: "0-", pokemon: ["Mega Excadrill"] },
  { spe: 220, boost: 2, evs: "0", pokemon: ["Hisuian Arcanine","Kangaskhan","Mega Chandelure","Pikachu","Roserade"] },
  { spe: 220, boost: 2, evs: "32", pokemon: ["Aurorus","Pangoro"] },
  { spe: 220, boost: 1, evs: "32", pokemon: ["Gliscor","Hisuian Typhlosion"] },
  { spe: 220, boost: 1, evs: "32", pokemon: ["Arcanine","Houndoom","Sharpedo"] },
  { spe: 219, boost: 1, evs: "32+", pokemon: ["Gyarados","Mega Gyarados"] },
  { spe: 219, boost: 1, evs: "0", pokemon: ["Talonflame"] },
  { spe: 219, boost: 1, evs: "32", pokemon: ["Tinkaton"] },
  { spe: 219, boost: 1, evs: "32+", pokemon: ["Milotic"] },
  { spe: 218, boost: 2, evs: "0-", pokemon: ["Garchomp","Mega Floette"] },
  { spe: 217, boost: 1, evs: "32+", pokemon: ["Dragonite","Gallade","Gardevoir","Mamoswine","Medicham","Mega Altaria"] },
  { spe: 217, boost: 1, evs: "0-", pokemon: ["Dragapult"] },
  { spe: 217, boost: 1, evs: "0", pokemon: ["Weavile"] },
  { spe: 217, boost: 1, evs: "32+", pokemon: ["Venusaur"] },
  { spe: 217, boost: 1, evs: "0-", pokemon: ["Mega Greninja"] },
  { spe: 217, boost: 1, evs: "32+", pokemon: ["Chandelure","Glalie","Goodra","Mega Meganium","Mega Venusaur","Meganium"] },
  { spe: 216, boost: 2, evs: "32", pokemon: ["Torterra"] },
  { spe: 216, boost: 2, evs: "0-", pokemon: ["Mega Glimmora","Mega Charizard X","Mega Dragonite","Mega Gardevoir","Mega Medicham","Volcarona"] },
  { spe: 216, boost: 2, evs: "0", pokemon: ["Excadrill"] },
  { spe: 216, boost: 2, evs: "0-", pokemon: ["Paldean Tauros","Typhlosion","Pidgeot","Charizard","Mega Charizard Y","Mega Glalie","Mega Kangaskhan","Ninetales","Palafin"] },
  { spe: 216, boost: 2, evs: "32", pokemon: ["Trevenant"] },
  { spe: 216, boost: 2, evs: "32+", pokemon: ["Hippowdon"] },
  { spe: 216, boost: 1, evs: "32+", pokemon: ["Vanilluxe"] },
  { spe: 216, boost: 1, evs: "0", pokemon: ["Mega Meowstic"] },
  { spe: 216, boost: 1, evs: "32", pokemon: ["Krookodile","Mega Garchomp"] },
  { spe: 216, boost: 0, evs: "32+", pokemon: ["Mega Beedrill"] },
  { spe: 214, boost: 2, evs: "0-", pokemon: ["Gourgeist-Small"] },
  { spe: 214, boost: 2, evs: "32", pokemon: ["Ampharos","Golurk","Machamp","Mega Golurk"] },
  { spe: 214, boost: 1, evs: "32+", pokemon: ["Basculegion","Blastoise","Diggersby","Feraligatr","Mega Blastoise","Mega Feraligatr"] },
  { spe: 214, boost: 1, evs: "0", pokemon: ["Meowscarada"] },
  { spe: 214, boost: 1, evs: "0", pokemon: ["Noivern"] },
  { spe: 213, boost: 1, evs: "32", pokemon: ["Lucario","Hisuian Arcanine"] },
  { spe: 213, boost: 1, evs: "0", pokemon: ["Greninja"] },
  { spe: 213, boost: 1, evs: "32", pokemon: ["Kangaskhan","Mega Chandelure","Pikachu","Roserade"] },
  { spe: 213, boost: 0, evs: "32+", pokemon: ["Dragapult","Mega Greninja"] },
  { spe: 212, boost: 2, evs: "32+", pokemon: ["Mega Ampharos"] },
  { spe: 212, boost: 2, evs: "0", pokemon: ["Glimmora"] },
  { spe: 212, boost: 2, evs: "0-", pokemon: ["Hydreigon"] },
  { spe: 212, boost: 2, evs: "0", pokemon: ["Rotom-Wash"] },
  { spe: 212, boost: 2, evs: "32", pokemon: ["Gourgeist-Super"] },
  { spe: 212, boost: 2, evs: "32+", pokemon: ["Bellibolt","Conkeldurr"] },
  { spe: 211, boost: 1, evs: "0", pokemon: ["Mega Pidgeot"] },
  { spe: 210, boost: 2, evs: "0", pokemon: ["Ceruledge","Kommo-o","Quaquaval"] },
  { spe: 210, boost: 2, evs: "0", pokemon: ["Heracross","Hisuian Samurott","Archaludon","Kleavor","Pinsir"] },
  { spe: 210, boost: 2, evs: "0-", pokemon: ["Morpeko"] },
  { spe: 210, boost: 2, evs: "32+", pokemon: ["Hydrapple","Mega Chesnaught"] },
  { spe: 210, boost: 1, evs: "0", pokemon: ["Mega Starmie","Sneasler"] },
  { spe: 210, boost: 1, evs: "32", pokemon: ["Excadrill"] },
  { spe: 210, boost: 1, evs: "0", pokemon: ["Alakazam","Mega Froslass"] },
  { spe: 208, boost: 2, evs: "0-", pokemon: ["Mimikyu"] },
  { spe: 208, boost: 2, evs: "0", pokemon: ["Gourgeist"] },
  { spe: 208, boost: 2, evs: "32+", pokemon: ["Crabominable"] },
  { spe: 208, boost: 1, evs: "32+", pokemon: ["Absol","Mega Heracross"] },
  { spe: 208, boost: 1, evs: "32+", pokemon: ["Armarouge"] },
  { spe: 208, boost: 1, evs: "0-", pokemon: ["Mega Lopunny","Mega Manectric"] },
  { spe: 208, boost: 1, evs: "32+", pokemon: ["Florges","Garbodor","Klefki","Mega Banette","Mega Emboar","Mega Scizor","Mega Scovillain","Scovillain"] },
  { spe: 207, boost: 1, evs: "32", pokemon: ["Glimmora","Rotom-Wash"] },
  { spe: 207, boost: 1, evs: "0", pokemon: ["Hawlucha"] },
  { spe: 207, boost: 1, evs: "0-", pokemon: ["Mega Delphox"] },
  { spe: 207, boost: 1, evs: "0", pokemon: ["Mega Hawlucha"] },
  { spe: 206, boost: 2, evs: "0-", pokemon: ["Gliscor"] },
  { spe: 206, boost: 2, evs: "0-", pokemon: ["Hisuian Typhlosion","Arcanine","Houndoom","Sharpedo"] },
  { spe: 206, boost: 2, evs: "32+", pokemon: ["Araquanid"] },
  { spe: 205, boost: 1, evs: "32", pokemon: ["Kommo-o","Quaquaval","Heracross","Hisuian Samurott"] },
  { spe: 205, boost: 1, evs: "32", pokemon: ["Ceruledge"] },
  { spe: 205, boost: 1, evs: "0", pokemon: ["Salazzle"] },
  { spe: 205, boost: 1, evs: "32", pokemon: ["Archaludon","Kleavor","Pinsir"] },
  { spe: 205, boost: 0, evs: "32+", pokemon: ["Mega Lopunny","Mega Manectric"] },
  { spe: 204, boost: 2, evs: "0-", pokemon: ["Tinkaton"] },
  { spe: 204, boost: 2, evs: "32", pokemon: ["Audino","Azumarill","Beartic","Kingambit","Mega Aggron","Mega Audino","Sableye","Sinistcha"] },
  { spe: 204, boost: 1, evs: "0", pokemon: ["Whimsicott"] },
  { spe: 204, boost: 1, evs: "32", pokemon: ["Gourgeist"] },
  { spe: 204, boost: 1, evs: "32+", pokemon: ["Slurpuff","Tsareena"] },
  { spe: 204, boost: 0, evs: "32+", pokemon: ["Mega Delphox"] },
  { spe: 202, boost: 2, evs: "32+", pokemon: ["Rhyperior"] },
  { spe: 202, boost: 2, evs: "0", pokemon: ["Gyarados","Mega Gyarados"] },
  { spe: 202, boost: 2, evs: "0", pokemon: ["Milotic"] },
  { spe: 202, boost: 2, evs: "32+", pokemon: ["Forretress"] },
  { spe: 202, boost: 1, evs: "32+", pokemon: ["Mega Tyranitar","Tyrantrum"] },
  { spe: 202, boost: 1, evs: "0-", pokemon: ["Aerodactyl"] },
  { spe: 202, boost: 1, evs: "0", pokemon: ["Starmie"] },
  { spe: 202, boost: 1, evs: "0-", pokemon: ["Jolteon","Mega Gengar"] },
  { spe: 202, boost: 1, evs: "0", pokemon: ["Mega Absol","Mega Houndoom"] },
  { spe: 202, boost: 1, evs: "32+", pokemon: ["Sandaconda"] },
  { spe: 202, boost: 0, evs: "32", pokemon: ["Mega Aerodactyl","Mega Alakazam"] },
  { spe: 201, boost: 1, evs: "32+", pokemon: ["Flapple"] },
  { spe: 201, boost: 1, evs: "32+", pokemon: ["Skarmory","Victreebel"] },
  { spe: 201, boost: 1, evs: "32+", pokemon: ["Decidueye","Mega Clefable","Mega Victreebel","Mr. Rime","Politoed","Polteageist"] },
  { spe: 200, boost: 2, evs: "0", pokemon: ["Dragonite","Gallade","Gardevoir","Mega Altaria","Venusaur"] },
  { spe: 200, boost: 2, evs: "0", pokemon: ["Mamoswine","Medicham","Chandelure","Glalie","Goodra","Mega Meganium","Mega Venusaur","Meganium"] },
  { spe: 200, boost: 2, evs: "0-", pokemon: ["Krookodile","Mega Garchomp"] },
  { spe: 200, boost: 0, evs: "32+", pokemon: ["Aerodactyl","Jolteon","Mega Gengar"] },
  { spe: 199, boost: 1, evs: "32", pokemon: ["Mega Gyarados"] },
  { spe: 199, boost: 1, evs: "32", pokemon: ["Gyarados"] },
  { spe: 199, boost: 1, evs: "0", pokemon: ["Serperior"] },
  { spe: 199, boost: 1, evs: "32", pokemon: ["Milotic"] },
  { spe: 199, boost: 1, evs: "32+", pokemon: ["Gourgeist-Large"] },
  { spe: 198, boost: 2, evs: "0-", pokemon: ["Lucario"] },
  { spe: 198, boost: 2, evs: "0-", pokemon: ["Hisuian Arcanine","Kangaskhan","Mega Chandelure","Pikachu","Roserade"] },
  { spe: 198, boost: 2, evs: "0", pokemon: ["Vanilluxe"] },
  { spe: 198, boost: 2, evs: "32", pokemon: ["Hippowdon"] },
  { spe: 198, boost: 2, evs: "32+", pokemon: ["Hisuian Avalugg"] },
  { spe: 198, boost: 1, evs: "32", pokemon: ["Dragonite","Mega Altaria"] },
  { spe: 198, boost: 1, evs: "32", pokemon: ["Gallade","Gardevoir","Mamoswine","Medicham"] },
  { spe: 198, boost: 1, evs: "0", pokemon: ["Lycanroc-Midday","Mega Lucario"] },
  { spe: 198, boost: 1, evs: "32", pokemon: ["Venusaur"] },
  { spe: 198, boost: 1, evs: "32", pokemon: ["Chandelure","Glalie","Goodra","Mega Meganium","Mega Venusaur","Meganium"] },
  { spe: 197, boost: 0, evs: "32", pokemon: ["Mega Beedrill"] },
  { spe: 196, boost: 2, evs: "0", pokemon: ["Basculegion","Blastoise","Diggersby","Feraligatr","Mega Blastoise","Mega Feraligatr"] },
  { spe: 196, boost: 1, evs: "0", pokemon: ["Maushold"] },
  { spe: 196, boost: 1, evs: "32", pokemon: ["Vanilluxe"] },
  { spe: 196, boost: 1, evs: "0-", pokemon: ["Talonflame"] },
  { spe: 195, boost: 1, evs: "32", pokemon: ["Basculegion","Blastoise","Diggersby","Feraligatr","Mega Blastoise","Mega Feraligatr"] },
  { spe: 195, boost: 1, evs: "0-", pokemon: ["Weavile"] },
  { spe: 195, boost: 1, evs: "0", pokemon: ["Gengar","Lycanroc-Dusk","Hisuian Zoroark"] },
  { spe: 195, boost: 1, evs: "0", pokemon: ["Mega Gallade","Mega Skarmory"] },
  { spe: 195, boost: 1, evs: "0", pokemon: ["Alolan Raichu","Espeon","Froslass","Raichu","Tauros"] },
  { spe: 195, boost: 1, evs: "32+", pokemon: ["Corviknight"] },
  { spe: 195, boost: 0, evs: "32+", pokemon: ["Talonflame"] },
  { spe: 194, boost: 2, evs: "32", pokemon: ["Mega Ampharos"] },
  { spe: 194, boost: 2, evs: "0-", pokemon: ["Excadrill"] },
  { spe: 194, boost: 2, evs: "32", pokemon: ["Bellibolt","Conkeldurr"] },
  { spe: 194, boost: 0, evs: "32", pokemon: ["Dragapult","Mega Greninja"] },
  { spe: 194, boost: 0, evs: "32+", pokemon: ["Weavile"] },
  { spe: 193, boost: 1, evs: "0", pokemon: ["Heliolisk"] },
  { spe: 193, boost: 1, evs: "0-", pokemon: ["Mega Meowstic"] },
  { spe: 193, boost: 1, evs: "0", pokemon: ["Alolan Ninetales"] },
  { spe: 193, boost: 1, evs: "32+", pokemon: ["Skeledirge"] },
  { spe: 193, boost: 0, evs: "32+", pokemon: ["Mega Meowstic"] },
  { spe: 192, boost: 2, evs: "32", pokemon: ["Hydrapple","Mega Chesnaught"] },
  { spe: 192, boost: 2, evs: "32+", pokemon: ["Drampa","Mega Drampa"] },
  { spe: 192, boost: 1, evs: "32+", pokemon: ["Scizor"] },
  { spe: 192, boost: 1, evs: "0-", pokemon: ["Meowscarada"] },
  { spe: 192, boost: 1, evs: "0", pokemon: ["Infernape"] },
  { spe: 192, boost: 1, evs: "0-", pokemon: ["Noivern"] },
  { spe: 192, boost: 1, evs: "32+", pokemon: ["Banette","Chimecho","Emboar","Mega Chimecho","Orthworm","Pelipper","Umbreon","Vaporeon"] },
  { spe: 192, boost: 0, evs: "32+", pokemon: ["Meowscarada","Noivern"] },
  { spe: 191, boost: 0, evs: "32+", pokemon: ["Greninja"] },
  { spe: 190, boost: 2, evs: "0-", pokemon: ["Glimmora"] },
  { spe: 190, boost: 2, evs: "0", pokemon: ["Armarouge"] },
  { spe: 190, boost: 2, evs: "0-", pokemon: ["Rotom-Wash"] },
  { spe: 190, boost: 2, evs: "0", pokemon: ["Absol","Mega Heracross","Florges","Garbodor","Klefki","Mega Banette","Mega Emboar","Mega Scizor","Mega Scovillain","Scovillain"] },
  { spe: 190, boost: 2, evs: "32", pokemon: ["Crabominable"] },
  { spe: 190, boost: 2, evs: "32+", pokemon: ["Garganacl","Mudsdale","Toxapex"] },
  { spe: 190, boost: 1, evs: "32", pokemon: ["Mega Heracross"] },
  { spe: 190, boost: 1, evs: "0-", pokemon: ["Greninja"] },
  { spe: 190, boost: 1, evs: "32", pokemon: ["Absol"] },
  { spe: 190, boost: 1, evs: "32", pokemon: ["Armarouge"] },
  { spe: 190, boost: 1, evs: "32", pokemon: ["Florges","Garbodor","Klefki","Mega Banette","Mega Emboar","Mega Scizor","Mega Scovillain","Scovillain"] },
  { spe: 190, boost: 1, evs: "32+", pokemon: ["Chesnaught"] },
  { spe: 190, boost: 0, evs: "32+", pokemon: ["Mega Pidgeot"] },
  { spe: 189, boost: 1, evs: "0-", pokemon: ["Mega Starmie","Sneasler"] },
  { spe: 189, boost: 1, evs: "0-", pokemon: ["Mega Pidgeot","Alakazam","Mega Froslass"] },
  { spe: 189, boost: 0, evs: "32+", pokemon: ["Alakazam","Mega Froslass","Mega Starmie","Sneasler"] },
  { spe: 188, boost: 2, evs: "0-", pokemon: ["Ceruledge","Kommo-o","Quaquaval"] },
  { spe: 188, boost: 2, evs: "0-", pokemon: ["Heracross","Hisuian Samurott","Archaludon","Kleavor","Pinsir"] },
  { spe: 188, boost: 2, evs: "32", pokemon: ["Araquanid"] },
  { spe: 187, boost: 1, evs: "0", pokemon: ["Espathra","Zoroark"] },
  { spe: 187, boost: 1, evs: "0", pokemon: ["Lopunny","Manectric","Mega Pinsir","Mega Sharpedo"] },
  { spe: 187, boost: 0, evs: "32", pokemon: ["Mega Lopunny","Mega Manectric"] },
  { spe: 187, boost: 0, evs: "32+", pokemon: ["Hawlucha","Mega Hawlucha"] },
  { spe: 186, boost: 2, evs: "0-", pokemon: ["Gourgeist"] },
  { spe: 186, boost: 2, evs: "32+", pokemon: ["Mega Crabominable"] },
  { spe: 186, boost: 1, evs: "0-", pokemon: ["Hawlucha"] },
  { spe: 186, boost: 1, evs: "0-", pokemon: ["Mega Hawlucha"] },
  { spe: 186, boost: 1, evs: "0", pokemon: ["Delphox","Meowstic"] },
  { spe: 186, boost: 1, evs: "32", pokemon: ["Slurpuff","Tsareena"] },
  { spe: 186, boost: 1, evs: "32+", pokemon: ["Tyranitar"] },
  { spe: 186, boost: 0, evs: "32", pokemon: ["Mega Delphox"] },
  { spe: 185, boost: 0, evs: "32+", pokemon: ["Salazzle"] },
  { spe: 184, boost: 2, evs: "32", pokemon: ["Rhyperior"] },
  { spe: 184, boost: 2, evs: "0", pokemon: ["Slurpuff","Tsareena"] },
  { spe: 184, boost: 2, evs: "32", pokemon: ["Forretress"] },
  { spe: 184, boost: 1, evs: "32", pokemon: ["Mega Tyranitar","Tyrantrum"] },
  { spe: 184, boost: 1, evs: "0", pokemon: ["Mega Excadrill"] },
  { spe: 184, boost: 1, evs: "32+", pokemon: ["Aegislash"] },
  { spe: 184, boost: 1, evs: "0-", pokemon: ["Salazzle"] },
  { spe: 184, boost: 1, evs: "32", pokemon: ["Sandaconda"] },
  { spe: 184, boost: 1, evs: "32+", pokemon: ["Abomasnow","Clefable","Empoleon","Hisuian Decidueye","Hisuian Goodra","Incineroar","Primarina","Sylveon"] },
  { spe: 184, boost: 0, evs: "32+", pokemon: ["Whimsicott"] },
  { spe: 183, boost: 1, evs: "32", pokemon: ["Flapple"] },
  { spe: 183, boost: 1, evs: "0", pokemon: ["Garchomp"] },
  { spe: 183, boost: 1, evs: "32", pokemon: ["Skarmory","Victreebel"] },
  { spe: 183, boost: 1, evs: "0-", pokemon: ["Whimsicott"] },
  { spe: 183, boost: 1, evs: "0", pokemon: ["Mega Floette"] },
  { spe: 183, boost: 1, evs: "32", pokemon: ["Decidueye","Mega Clefable","Mega Victreebel","Mr. Rime","Politoed","Polteageist"] },
  { spe: 183, boost: 0, evs: "32+", pokemon: ["Mega Absol","Mega Houndoom","Starmie"] },
  { spe: 182, boost: 2, evs: "0", pokemon: ["Mega Tyranitar","Tyrantrum"] },
  { spe: 182, boost: 2, evs: "0", pokemon: ["Sandaconda"] },
  { spe: 182, boost: 0, evs: "32", pokemon: ["Aerodactyl","Jolteon","Mega Gengar"] },
  { spe: 181, boost: 1, evs: "0", pokemon: ["Mega Glimmora"] },
  { spe: 181, boost: 1, evs: "0-", pokemon: ["Starmie"] },
  { spe: 181, boost: 1, evs: "0-", pokemon: ["Mega Absol","Mega Houndoom"] },
  { spe: 181, boost: 1, evs: "0", pokemon: ["Pidgeot"] },
  { spe: 181, boost: 1, evs: "32", pokemon: ["Gourgeist-Large"] },
  { spe: 181, boost: 1, evs: "32+", pokemon: ["Aurorus","Pangoro"] },
  { spe: 181, boost: 0, evs: "32+", pokemon: ["Serperior"] },
  { spe: 180, boost: 2, evs: "0-", pokemon: ["Gyarados","Mega Gyarados","Dragonite","Gallade","Gardevoir","Mega Altaria","Venusaur"] },
  { spe: 180, boost: 2, evs: "0", pokemon: ["Flapple","Skarmory","Victreebel"] },
  { spe: 180, boost: 2, evs: "0-", pokemon: ["Mamoswine","Medicham","Milotic","Chandelure","Glalie","Goodra","Mega Meganium","Mega Venusaur","Meganium"] },
  { spe: 180, boost: 2, evs: "0", pokemon: ["Decidueye","Mega Clefable","Mega Victreebel","Mr. Rime","Politoed","Polteageist"] },
  { spe: 180, boost: 2, evs: "32", pokemon: ["Hisuian Avalugg"] },
  { spe: 180, boost: 2, evs: "32+", pokemon: ["Cofagrigus","Galarian Slowbro","Galarian Slowking","Mega Abomasnow","Mega Slowbro","Mega Steelix","Reuniclus","Slowbro","Slowking","Snorlax"] },
  { spe: 180, boost: 1, evs: "0", pokemon: ["Mega Charizard X","Mega Dragonite","Mega Medicham","Volcarona","Paldean Tauros","Typhlosion"] },
  { spe: 180, boost: 1, evs: "0", pokemon: ["Mega Gardevoir"] },
  { spe: 180, boost: 1, evs: "0", pokemon: ["Charizard","Mega Charizard Y","Mega Glalie","Mega Kangaskhan","Ninetales","Palafin"] },
  { spe: 180, boost: 0, evs: "32+", pokemon: ["Lycanroc-Midday","Mega Lucario"] },
  { spe: 179, boost: 0, evs: "32+", pokemon: ["Maushold"] },
  { spe: 178, boost: 2, evs: "0-", pokemon: ["Vanilluxe"] },
  { spe: 178, boost: 2, evs: "0", pokemon: ["Gourgeist-Large"] },
  { spe: 178, boost: 2, evs: "32+", pokemon: ["Hatterene"] },
  { spe: 178, boost: 1, evs: "0-", pokemon: ["Serperior"] },
  { spe: 178, boost: 1, evs: "0", pokemon: ["Gourgeist-Small"] },
  { spe: 178, boost: 1, evs: "32", pokemon: ["Corviknight"] },
  { spe: 178, boost: 0, evs: "32", pokemon: ["Talonflame"] },
  { spe: 178, boost: 0, evs: "32+", pokemon: ["Alolan Raichu","Espeon","Froslass","Gengar","Lycanroc-Dusk","Mega Gallade","Mega Skarmory","Raichu","Tauros","Hisuian Zoroark"] },
  { spe: 177, boost: 1, evs: "0", pokemon: ["Hydreigon"] },
  { spe: 177, boost: 1, evs: "0-", pokemon: ["Lycanroc-Midday","Mega Lucario"] },
  { spe: 177, boost: 1, evs: "32+", pokemon: ["Torterra"] },
  { spe: 177, boost: 1, evs: "32", pokemon: ["Skeledirge"] },
  { spe: 177, boost: 1, evs: "32+", pokemon: ["Trevenant"] },
  { spe: 177, boost: 0, evs: "32", pokemon: ["Weavile"] },
  { spe: 177, boost: 0, evs: "32+", pokemon: ["Alolan Ninetales","Heliolisk"] },
  { spe: 176, boost: 2, evs: "0-", pokemon: ["Basculegion","Blastoise","Diggersby","Feraligatr","Mega Blastoise","Mega Feraligatr"] },
  { spe: 176, boost: 2, evs: "32", pokemon: ["Drampa","Mega Drampa"] },
  { spe: 176, boost: 0, evs: "32", pokemon: ["Mega Meowstic"] },
  { spe: 176, boost: 0, evs: "32+", pokemon: ["Infernape"] },
  { spe: 175, boost: 1, evs: "32", pokemon: ["Scizor"] },
  { spe: 175, boost: 1, evs: "0-", pokemon: ["Maushold","Gengar","Lycanroc-Dusk","Hisuian Zoroark"] },
  { spe: 175, boost: 1, evs: "0-", pokemon: ["Mega Gallade","Mega Skarmory"] },
  { spe: 175, boost: 1, evs: "0-", pokemon: ["Alolan Raichu","Espeon","Froslass","Raichu","Tauros"] },
  { spe: 175, boost: 1, evs: "0", pokemon: ["Morpeko"] },
  { spe: 175, boost: 1, evs: "32", pokemon: ["Banette","Chimecho","Emboar","Mega Chimecho","Orthworm","Pelipper","Umbreon","Vaporeon"] },
  { spe: 175, boost: 1, evs: "32+", pokemon: ["Ampharos","Golurk","Machamp","Mega Golurk"] },
  { spe: 175, boost: 0, evs: "32", pokemon: ["Meowscarada","Noivern"] },
  { spe: 174, boost: 2, evs: "0", pokemon: ["Corviknight"] },
  { spe: 174, boost: 2, evs: "32", pokemon: ["Garganacl","Mudsdale","Toxapex"] },
  { spe: 174, boost: 1, evs: "0-", pokemon: ["Heliolisk"] },
  { spe: 174, boost: 1, evs: "0-", pokemon: ["Alolan Ninetales"] },
  { spe: 174, boost: 1, evs: "0", pokemon: ["Mimikyu"] },
  { spe: 174, boost: 1, evs: "32", pokemon: ["Chesnaught"] },
  { spe: 174, boost: 1, evs: "32+", pokemon: ["Gourgeist-Super"] },
  { spe: 174, boost: 0, evs: "32", pokemon: ["Greninja"] },
  { spe: 173, boost: 0, evs: "32", pokemon: ["Mega Pidgeot"] },
  { spe: 172, boost: 2, evs: "0", pokemon: ["Skeledirge"] },
  { spe: 172, boost: 1, evs: "0", pokemon: ["Gliscor","Hisuian Typhlosion"] },
  { spe: 172, boost: 1, evs: "0-", pokemon: ["Infernape"] },
  { spe: 172, boost: 1, evs: "0", pokemon: ["Arcanine","Houndoom","Sharpedo"] },
  { spe: 172, boost: 0, evs: "32", pokemon: ["Alakazam","Mega Froslass","Mega Starmie","Sneasler"] },
  { spe: 172, boost: 0, evs: "32+", pokemon: ["Espathra","Lopunny","Manectric","Mega Pinsir","Mega Sharpedo","Zoroark"] },
  { spe: 171, boost: 1, evs: "0", pokemon: ["Tinkaton"] },
  { spe: 171, boost: 0, evs: "32+", pokemon: ["Delphox","Meowstic"] },
  { spe: 170, boost: 2, evs: "0-", pokemon: ["Armarouge"] },
  { spe: 170, boost: 2, evs: "0-", pokemon: ["Absol","Mega Heracross","Florges","Garbodor","Klefki","Mega Banette","Mega Emboar","Mega Scizor","Mega Scovillain","Scovillain"] },
  { spe: 170, boost: 2, evs: "0", pokemon: ["Scizor","Banette","Chimecho","Emboar","Mega Chimecho","Orthworm","Pelipper","Umbreon","Vaporeon"] },
  { spe: 170, boost: 2, evs: "32", pokemon: ["Mega Crabominable"] },
  { spe: 170, boost: 0, evs: "32", pokemon: ["Hawlucha"] },
  { spe: 170, boost: 0, evs: "32+", pokemon: ["Mega Excadrill"] },
  { spe: 170, boost: 0, evs: "0", pokemon: ["Mega Aerodactyl","Mega Alakazam"] },
  { spe: 170, boost: 0, evs: "32", pokemon: ["Mega Hawlucha"] },
  { spe: 169, boost: 1, evs: "32", pokemon: ["Tyranitar"] },
  { spe: 169, boost: 0, evs: "32+", pokemon: ["Garchomp","Mega Floette"] },
  { spe: 169, boost: 0, evs: "32", pokemon: ["Salazzle"] },
  { spe: 168, boost: 2, evs: "0", pokemon: ["Chesnaught"] },
  { spe: 168, boost: 1, evs: "0-", pokemon: ["Espathra","Zoroark"] },
  { spe: 168, boost: 1, evs: "32", pokemon: ["Aegislash"] },
  { spe: 168, boost: 1, evs: "0-", pokemon: ["Lopunny","Manectric","Mega Pinsir","Mega Sharpedo"] },
  { spe: 168, boost: 1, evs: "0", pokemon: ["Krookodile","Mega Garchomp"] },
  { spe: 168, boost: 1, evs: "32", pokemon: ["Abomasnow","Clefable","Empoleon","Hisuian Decidueye","Hisuian Goodra","Incineroar","Primarina","Sylveon"] },
  { spe: 168, boost: 1, evs: "32+", pokemon: ["Audino","Azumarill","Beartic","Kingambit","Mega Aggron","Mega Audino","Sableye","Sinistcha"] },
  { spe: 168, boost: 0, evs: "32+", pokemon: ["Mega Glimmora","Pidgeot"] },
  { spe: 168, boost: 0, evs: "32", pokemon: ["Whimsicott"] },
  { spe: 167, boost: 0, evs: "32+", pokemon: ["Charizard","Mega Charizard X","Mega Charizard Y","Mega Dragonite","Mega Gardevoir","Mega Glalie","Mega Kangaskhan","Mega Medicham","Ninetales","Palafin","Paldean Tauros","Typhlosion","Volcarona"] },
  { spe: 167, boost: 0, evs: "32", pokemon: ["Starmie","Mega Absol","Mega Houndoom"] },
  { spe: 166, boost: 1, evs: "0-", pokemon: ["Delphox","Meowstic"] },
  { spe: 166, boost: 0, evs: "32+", pokemon: ["Gourgeist-Small"] },
  { spe: 165, boost: 1, evs: "0", pokemon: ["Lucario","Hisuian Arcanine"] },
  { spe: 165, boost: 1, evs: "0-", pokemon: ["Mega Excadrill"] },
  { spe: 165, boost: 1, evs: "0", pokemon: ["Kangaskhan","Mega Chandelure","Pikachu","Roserade"] },
  { spe: 165, boost: 1, evs: "32", pokemon: ["Aurorus","Pangoro"] },
  { spe: 165, boost: 0, evs: "32+", pokemon: ["Hydreigon"] },
  { spe: 165, boost: 0, evs: "32", pokemon: ["Serperior"] },
  { spe: 165, boost: 0, evs: "0", pokemon: ["Mega Beedrill"] },
  { spe: 164, boost: 2, evs: "0-", pokemon: ["Slurpuff","Tsareena"] },
  { spe: 164, boost: 2, evs: "32", pokemon: ["Cofagrigus","Galarian Slowbro","Galarian Slowking","Mega Abomasnow","Mega Slowbro","Mega Steelix","Reuniclus","Slowbro","Slowking","Snorlax"] },
  { spe: 164, boost: 0, evs: "32", pokemon: ["Lycanroc-Midday","Mega Lucario"] },
  { spe: 163, boost: 1, evs: "0-", pokemon: ["Garchomp"] },
  { spe: 163, boost: 1, evs: "0-", pokemon: ["Mega Floette"] },
  { spe: 163, boost: 0, evs: "32+", pokemon: ["Morpeko"] },
  { spe: 163, boost: 0, evs: "32", pokemon: ["Maushold"] },
  { spe: 162, boost: 2, evs: "0-", pokemon: ["Mega Tyranitar","Tyrantrum","Flapple","Skarmory","Victreebel"] },
  { spe: 162, boost: 2, evs: "0-", pokemon: ["Sandaconda","Decidueye","Mega Clefable","Mega Victreebel","Mr. Rime","Politoed","Polteageist"] },
  { spe: 162, boost: 2, evs: "0", pokemon: ["Tyranitar"] },
  { spe: 162, boost: 2, evs: "32", pokemon: ["Hatterene"] },
  { spe: 162, boost: 1, evs: "0-", pokemon: ["Mega Glimmora","Mega Charizard X","Mega Dragonite","Mega Medicham","Volcarona","Paldean Tauros","Typhlosion"] },
  { spe: 162, boost: 1, evs: "0", pokemon: ["Excadrill"] },
  { spe: 162, boost: 1, evs: "0-", pokemon: ["Mega Gardevoir"] },
  { spe: 162, boost: 1, evs: "32", pokemon: ["Torterra"] },
  { spe: 162, boost: 1, evs: "0-", pokemon: ["Pidgeot","Charizard","Mega Charizard Y","Mega Glalie","Mega Kangaskhan","Ninetales","Palafin"] },
  { spe: 162, boost: 1, evs: "32", pokemon: ["Trevenant"] },
  { spe: 162, boost: 1, evs: "32+", pokemon: ["Hippowdon"] },
  { spe: 162, boost: 0, evs: "32+", pokemon: ["Mimikyu"] },
  { spe: 162, boost: 0, evs: "0", pokemon: ["Dragapult","Mega Greninja"] },
  { spe: 162, boost: 0, evs: "32", pokemon: ["Mega Gallade","Mega Skarmory","Gengar","Lycanroc-Dusk","Hisuian Zoroark","Alolan Raichu","Espeon","Froslass","Raichu","Tauros"] },
  { spe: 161, boost: 0, evs: "32+", pokemon: ["Arcanine","Gliscor","Hisuian Typhlosion","Houndoom","Sharpedo"] },
  { spe: 161, boost: 0, evs: "32", pokemon: ["Heliolisk","Alolan Ninetales"] },
  { spe: 160, boost: 2, evs: "0", pokemon: ["Aegislash"] },
  { spe: 160, boost: 2, evs: "0-", pokemon: ["Gourgeist-Large"] },
  { spe: 160, boost: 2, evs: "0", pokemon: ["Abomasnow","Clefable","Empoleon","Hisuian Decidueye","Hisuian Goodra","Incineroar","Primarina","Sylveon"] },
  { spe: 160, boost: 1, evs: "0-", pokemon: ["Gourgeist-Small"] },
  { spe: 160, boost: 1, evs: "32", pokemon: ["Ampharos","Golurk","Machamp","Mega Golurk"] },
  { spe: 160, boost: 0, evs: "32+", pokemon: ["Tinkaton"] },
  { spe: 160, boost: 0, evs: "32", pokemon: ["Infernape"] },
  { spe: 159, boost: 1, evs: "0", pokemon: ["Glimmora"] },
  { spe: 159, boost: 1, evs: "0-", pokemon: ["Hydreigon"] },
  { spe: 159, boost: 1, evs: "0", pokemon: ["Rotom-Wash"] },
  { spe: 159, boost: 1, evs: "32+", pokemon: ["Mega Ampharos"] },
  { spe: 159, boost: 1, evs: "32", pokemon: ["Gourgeist-Super"] },
  { spe: 159, boost: 1, evs: "32+", pokemon: ["Bellibolt","Conkeldurr"] },
  { spe: 158, boost: 2, evs: "32+", pokemon: ["Mega Camerupt","Mega Sableye","Torkoal"] },
  { spe: 158, boost: 0, evs: "32+", pokemon: ["Krookodile","Mega Garchomp"] },
  { spe: 157, boost: 1, evs: "0", pokemon: ["Kommo-o","Quaquaval","Heracross","Hisuian Samurott"] },
  { spe: 157, boost: 1, evs: "0", pokemon: ["Ceruledge"] },
  { spe: 157, boost: 1, evs: "0-", pokemon: ["Morpeko"] },
  { spe: 157, boost: 1, evs: "0", pokemon: ["Archaludon","Kleavor","Pinsir"] },
  { spe: 157, boost: 1, evs: "32+", pokemon: ["Hydrapple","Mega Chesnaught"] },
  { spe: 157, boost: 0, evs: "32", pokemon: ["Espathra","Zoroark","Lopunny","Manectric","Mega Pinsir","Mega Sharpedo"] },
  { spe: 156, boost: 2, evs: "0-", pokemon: ["Corviknight"] },
  { spe: 156, boost: 2, evs: "0", pokemon: ["Aurorus","Pangoro"] },
  { spe: 156, boost: 1, evs: "0-", pokemon: ["Mimikyu"] },
  { spe: 156, boost: 1, evs: "0", pokemon: ["Gourgeist"] },
  { spe: 156, boost: 1, evs: "32+", pokemon: ["Crabominable"] },
  { spe: 156, boost: 0, evs: "32+", pokemon: ["Hisuian Arcanine","Kangaskhan","Lucario","Mega Chandelure","Pikachu","Roserade"] },
  { spe: 156, boost: 0, evs: "32", pokemon: ["Delphox","Meowstic"] },
  { spe: 155, boost: 0, evs: "32", pokemon: ["Mega Excadrill"] },
  { spe: 155, boost: 0, evs: "0", pokemon: ["Mega Lopunny","Mega Manectric"] },
  { spe: 154, boost: 2, evs: "0-", pokemon: ["Skeledirge"] },
  { spe: 154, boost: 1, evs: "0-", pokemon: ["Gliscor","Hisuian Typhlosion"] },
  { spe: 154, boost: 1, evs: "0-", pokemon: ["Arcanine","Houndoom","Sharpedo"] },
  { spe: 154, boost: 1, evs: "32+", pokemon: ["Araquanid"] },
  { spe: 154, boost: 0, evs: "32+", pokemon: ["Excadrill"] },
  { spe: 154, boost: 0, evs: "32", pokemon: ["Garchomp","Mega Floette"] },
  { spe: 154, boost: 0, evs: "0", pokemon: ["Mega Delphox"] },
  { spe: 153, boost: 1, evs: "0-", pokemon: ["Tinkaton"] },
  { spe: 153, boost: 1, evs: "32", pokemon: ["Audino","Azumarill","Beartic","Kingambit","Mega Aggron","Mega Audino","Sableye","Sinistcha"] },
  { spe: 153, boost: 0, evs: "32", pokemon: ["Mega Glimmora","Pidgeot"] },
  { spe: 153, boost: 0, evs: "0-", pokemon: ["Mega Aerodactyl","Mega Alakazam"] },
  { spe: 152, boost: 2, evs: "0", pokemon: ["Torterra"] },
  { spe: 152, boost: 2, evs: "0-", pokemon: ["Scizor","Banette","Chimecho","Emboar","Mega Chimecho","Orthworm","Pelipper","Umbreon","Vaporeon"] },
  { spe: 152, boost: 2, evs: "0", pokemon: ["Trevenant"] },
  { spe: 152, boost: 0, evs: "32", pokemon: ["Mega Charizard X","Mega Dragonite"] },
  { spe: 152, boost: 0, evs: "32", pokemon: ["Mega Gardevoir","Mega Medicham","Volcarona","Paldean Tauros","Typhlosion","Charizard","Mega Charizard Y","Mega Glalie","Mega Kangaskhan","Ninetales","Palafin"] },
  { spe: 151, boost: 1, evs: "0", pokemon: ["Gyarados","Mega Gyarados"] },
  { spe: 151, boost: 1, evs: "32+", pokemon: ["Rhyperior"] },
  { spe: 151, boost: 1, evs: "0", pokemon: ["Milotic"] },
  { spe: 151, boost: 1, evs: "32+", pokemon: ["Forretress"] },
  { spe: 151, boost: 0, evs: "32+", pokemon: ["Rotom-Wash","Glimmora"] },
  { spe: 151, boost: 0, evs: "32", pokemon: ["Gourgeist-Small"] },
  { spe: 150, boost: 2, evs: "0-", pokemon: ["Chesnaught"] },
  { spe: 150, boost: 2, evs: "0", pokemon: ["Ampharos","Golurk","Machamp","Mega Golurk"] },
  { spe: 150, boost: 1, evs: "0", pokemon: ["Dragonite","Gallade","Gardevoir","Mega Altaria","Mamoswine","Medicham"] },
  { spe: 150, boost: 1, evs: "0", pokemon: ["Venusaur"] },
  { spe: 150, boost: 1, evs: "0-", pokemon: ["Krookodile","Mega Garchomp"] },
  { spe: 150, boost: 1, evs: "0", pokemon: ["Chandelure","Glalie","Goodra","Mega Meganium","Mega Venusaur","Meganium"] },
  { spe: 150, boost: 0, evs: "32+", pokemon: ["Archaludon","Ceruledge","Heracross","Hisuian Samurott","Kleavor","Kommo-o","Pinsir","Quaquaval"] },
  { spe: 150, boost: 0, evs: "0", pokemon: ["Aerodactyl","Jolteon","Mega Gengar"] },
  { spe: 150, boost: 0, evs: "32", pokemon: ["Hydreigon"] },
  { spe: 149, boost: 0, evs: "32+", pokemon: ["Gourgeist"] },
  { spe: 149, boost: 0, evs: "32", pokemon: ["Morpeko"] },
  { spe: 148, boost: 2, evs: "0", pokemon: ["Gourgeist-Super"] },
  { spe: 148, boost: 1, evs: "0-", pokemon: ["Lucario","Hisuian Arcanine"] },
  { spe: 148, boost: 1, evs: "0", pokemon: ["Vanilluxe"] },
  { spe: 148, boost: 1, evs: "0-", pokemon: ["Kangaskhan","Mega Chandelure","Pikachu","Roserade"] },
  { spe: 148, boost: 1, evs: "32", pokemon: ["Hippowdon"] },
  { spe: 148, boost: 1, evs: "32+", pokemon: ["Hisuian Avalugg"] },
  { spe: 148, boost: 0, evs: "0-", pokemon: ["Mega Beedrill"] },
  { spe: 148, boost: 0, evs: "32", pokemon: ["Mimikyu"] },
  { spe: 147, boost: 1, evs: "0", pokemon: ["Basculegion","Blastoise","Diggersby","Feraligatr","Mega Blastoise","Mega Feraligatr"] },
  { spe: 147, boost: 0, evs: "32", pokemon: ["Gliscor","Hisuian Typhlosion","Arcanine","Houndoom","Sharpedo"] },
  { spe: 146, boost: 0, evs: "32+", pokemon: ["Gyarados","Mega Gyarados","Milotic"] },
  { spe: 146, boost: 0, evs: "0", pokemon: ["Talonflame"] },
  { spe: 146, boost: 0, evs: "32", pokemon: ["Tinkaton"] },
  { spe: 145, boost: 1, evs: "0-", pokemon: ["Excadrill"] },
  { spe: 145, boost: 1, evs: "32", pokemon: ["Mega Ampharos"] },
  { spe: 145, boost: 1, evs: "32", pokemon: ["Bellibolt","Conkeldurr"] },
  { spe: 145, boost: 0, evs: "32+", pokemon: ["Chandelure","Dragonite","Gallade","Gardevoir","Glalie","Goodra","Mamoswine","Medicham","Mega Altaria","Mega Meganium","Mega Venusaur","Meganium","Venusaur"] },
  { spe: 145, boost: 0, evs: "0-", pokemon: ["Dragapult","Mega Greninja"] },
  { spe: 145, boost: 0, evs: "0", pokemon: ["Weavile"] },
  { spe: 144, boost: 2, evs: "0-", pokemon: ["Aegislash"] },
  { spe: 144, boost: 2, evs: "0-", pokemon: ["Tyranitar","Abomasnow","Clefable","Empoleon","Hisuian Decidueye","Hisuian Goodra","Incineroar","Primarina","Sylveon"] },
  { spe: 144, boost: 2, evs: "32", pokemon: ["Mega Camerupt","Mega Sableye","Torkoal"] },
  { spe: 144, boost: 1, evs: "32", pokemon: ["Hydrapple","Mega Chesnaught"] },
  { spe: 144, boost: 1, evs: "32+", pokemon: ["Drampa","Mega Drampa"] },
  { spe: 144, boost: 0, evs: "32+", pokemon: ["Vanilluxe"] },
  { spe: 144, boost: 0, evs: "0", pokemon: ["Mega Meowstic"] },
  { spe: 144, boost: 0, evs: "32", pokemon: ["Krookodile","Mega Garchomp"] },
  { spe: 143, boost: 0, evs: "32+", pokemon: ["Basculegion","Blastoise","Diggersby","Feraligatr","Mega Blastoise","Mega Feraligatr"] },
  { spe: 143, boost: 0, evs: "0", pokemon: ["Meowscarada","Noivern"] },
  { spe: 142, boost: 1, evs: "0-", pokemon: ["Glimmora","Rotom-Wash"] },
  { spe: 142, boost: 1, evs: "0", pokemon: ["Absol","Mega Heracross"] },
  { spe: 142, boost: 1, evs: "0", pokemon: ["Armarouge"] },
  { spe: 142, boost: 1, evs: "0", pokemon: ["Florges","Garbodor","Klefki","Mega Banette","Mega Emboar","Mega Scizor","Mega Scovillain","Scovillain"] },
  { spe: 142, boost: 1, evs: "32", pokemon: ["Crabominable"] },
  { spe: 142, boost: 1, evs: "32+", pokemon: ["Garganacl","Mudsdale","Toxapex"] },
  { spe: 142, boost: 0, evs: "32", pokemon: ["Lucario","Hisuian Arcanine","Kangaskhan","Mega Chandelure","Pikachu","Roserade"] },
  { spe: 142, boost: 0, evs: "0", pokemon: ["Greninja"] },
  { spe: 141, boost: 1, evs: "0-", pokemon: ["Kommo-o","Quaquaval","Heracross","Hisuian Samurott"] },
  { spe: 141, boost: 1, evs: "0-", pokemon: ["Ceruledge"] },
  { spe: 141, boost: 1, evs: "0-", pokemon: ["Archaludon","Kleavor","Pinsir"] },
  { spe: 141, boost: 1, evs: "32", pokemon: ["Araquanid"] },
  { spe: 141, boost: 0, evs: "0", pokemon: ["Mega Pidgeot"] },
  { spe: 140, boost: 2, evs: "0-", pokemon: ["Aurorus","Pangoro"] },
  { spe: 140, boost: 2, evs: "0", pokemon: ["Audino","Azumarill","Beartic","Kingambit","Mega Aggron","Mega Audino","Sableye","Sinistcha"] },
  { spe: 140, boost: 0, evs: "0", pokemon: ["Mega Starmie","Sneasler","Alakazam","Mega Froslass"] },
  { spe: 140, boost: 0, evs: "32", pokemon: ["Excadrill"] },
  { spe: 139, boost: 1, evs: "0-", pokemon: ["Gourgeist"] },
  { spe: 139, boost: 1, evs: "32+", pokemon: ["Mega Crabominable"] },
  { spe: 139, boost: 0, evs: "32+", pokemon: ["Absol","Armarouge","Florges","Garbodor","Klefki","Mega Banette","Mega Emboar","Mega Heracross","Mega Scizor","Mega Scovillain","Scovillain"] },
  { spe: 139, boost: 0, evs: "0-", pokemon: ["Mega Lopunny","Mega Manectric"] },
  { spe: 138, boost: 1, evs: "32", pokemon: ["Rhyperior"] },
  { spe: 138, boost: 1, evs: "0", pokemon: ["Slurpuff","Tsareena"] },
  { spe: 138, boost: 1, evs: "32", pokemon: ["Forretress"] },
  { spe: 138, boost: 0, evs: "0", pokemon: ["Hawlucha","Mega Hawlucha"] },
  { spe: 138, boost: 0, evs: "32", pokemon: ["Glimmora","Rotom-Wash"] },
  { spe: 138, boost: 0, evs: "0-", pokemon: ["Mega Delphox"] },
  { spe: 137, boost: 0, evs: "32", pokemon: ["Ceruledge","Kommo-o","Quaquaval","Heracross","Hisuian Samurott","Archaludon","Kleavor","Pinsir"] },
  { spe: 137, boost: 0, evs: "0", pokemon: ["Salazzle"] },
  { spe: 136, boost: 2, evs: "0-", pokemon: ["Torterra"] },
  { spe: 136, boost: 2, evs: "0-", pokemon: ["Trevenant"] },
  { spe: 136, boost: 1, evs: "0", pokemon: ["Mega Tyranitar","Tyrantrum"] },
  { spe: 136, boost: 1, evs: "0", pokemon: ["Sandaconda"] },
  { spe: 136, boost: 0, evs: "32+", pokemon: ["Slurpuff","Tsareena"] },
  { spe: 136, boost: 0, evs: "0", pokemon: ["Whimsicott"] },
  { spe: 136, boost: 0, evs: "32", pokemon: ["Gourgeist"] },
  { spe: 135, boost: 1, evs: "0-", pokemon: ["Gyarados","Mega Gyarados","Dragonite","Gallade","Gardevoir","Mega Altaria","Mamoswine","Medicham"] },
  { spe: 135, boost: 1, evs: "0", pokemon: ["Flapple"] },
  { spe: 135, boost: 1, evs: "0-", pokemon: ["Venusaur"] },
  { spe: 135, boost: 1, evs: "0", pokemon: ["Skarmory","Victreebel"] },
  { spe: 135, boost: 1, evs: "0-", pokemon: ["Milotic","Chandelure","Glalie","Goodra","Mega Meganium","Mega Venusaur","Meganium"] },
  { spe: 135, boost: 1, evs: "0", pokemon: ["Decidueye","Mega Clefable","Mega Victreebel","Mr. Rime","Politoed","Polteageist"] },
  { spe: 135, boost: 1, evs: "32", pokemon: ["Hisuian Avalugg"] },
  { spe: 135, boost: 1, evs: "32+", pokemon: ["Cofagrigus","Galarian Slowbro","Galarian Slowking","Mega Abomasnow","Mega Slowbro","Mega Steelix","Reuniclus","Slowbro","Slowking","Snorlax"] },
  { spe: 135, boost: 0, evs: "32+", pokemon: ["Mega Tyranitar","Sandaconda","Tyrantrum"] },
  { spe: 135, boost: 0, evs: "0-", pokemon: ["Aerodactyl","Jolteon","Mega Gengar"] },
  { spe: 135, boost: 0, evs: "0", pokemon: ["Starmie","Mega Absol","Mega Houndoom"] },
  { spe: 134, boost: 2, evs: "0-", pokemon: ["Ampharos","Golurk","Machamp","Mega Golurk"] },
  { spe: 134, boost: 2, evs: "0", pokemon: ["Hippowdon"] },
  { spe: 134, boost: 0, evs: "32+", pokemon: ["Decidueye","Flapple","Mega Clefable","Mega Victreebel","Mr. Rime","Politoed","Polteageist","Skarmory","Victreebel"] },
  { spe: 133, boost: 1, evs: "0-", pokemon: ["Vanilluxe"] },
  { spe: 133, boost: 1, evs: "0", pokemon: ["Gourgeist-Large"] },
  { spe: 133, boost: 1, evs: "32+", pokemon: ["Hatterene"] },
  { spe: 133, boost: 0, evs: "32", pokemon: ["Mega Gyarados"] },
  { spe: 133, boost: 0, evs: "32+", pokemon: ["Gourgeist-Large"] },
  { spe: 133, boost: 0, evs: "32", pokemon: ["Gyarados","Milotic"] },
  { spe: 133, boost: 0, evs: "0", pokemon: ["Serperior"] },
  { spe: 132, boost: 2, evs: "0-", pokemon: ["Gourgeist-Super"] },
  { spe: 132, boost: 1, evs: "0-", pokemon: ["Basculegion","Blastoise","Diggersby","Feraligatr","Mega Blastoise","Mega Feraligatr"] },
  { spe: 132, boost: 1, evs: "32", pokemon: ["Drampa","Mega Drampa"] },
  { spe: 132, boost: 0, evs: "32", pokemon: ["Dragonite","Mega Altaria","Venusaur"] },
  { spe: 132, boost: 0, evs: "0", pokemon: ["Lycanroc-Midday","Mega Lucario"] },
  { spe: 132, boost: 0, evs: "32", pokemon: ["Gallade","Gardevoir","Mamoswine","Medicham","Chandelure","Glalie","Goodra","Mega Meganium","Mega Venusaur","Meganium"] },
  { spe: 131, boost: 0, evs: "0", pokemon: ["Maushold"] },
  { spe: 131, boost: 0, evs: "32", pokemon: ["Vanilluxe"] },
  { spe: 131, boost: 0, evs: "0-", pokemon: ["Talonflame"] },
  { spe: 130, boost: 2, evs: "0", pokemon: ["Mega Ampharos"] },
  { spe: 130, boost: 2, evs: "0", pokemon: ["Bellibolt","Conkeldurr"] },
  { spe: 130, boost: 1, evs: "0", pokemon: ["Corviknight"] },
  { spe: 130, boost: 1, evs: "32", pokemon: ["Garganacl","Mudsdale","Toxapex"] },
  { spe: 130, boost: 0, evs: "32", pokemon: ["Basculegion","Blastoise","Diggersby","Feraligatr","Mega Blastoise","Mega Feraligatr"] },
  { spe: 130, boost: 0, evs: "32+", pokemon: ["Corviknight"] },
  { spe: 130, boost: 0, evs: "0", pokemon: ["Mega Gallade","Mega Skarmory","Gengar","Lycanroc-Dusk","Hisuian Zoroark","Alolan Raichu","Espeon","Froslass","Raichu","Tauros"] },
  { spe: 130, boost: 0, evs: "0-", pokemon: ["Weavile"] },
  { spe: 129, boost: 1, evs: "0", pokemon: ["Skeledirge"] },
  { spe: 129, boost: 0, evs: "32+", pokemon: ["Skeledirge"] },
  { spe: 129, boost: 0, evs: "0-", pokemon: ["Mega Meowstic"] },
  { spe: 129, boost: 0, evs: "0", pokemon: ["Heliolisk","Alolan Ninetales"] },
  { spe: 128, boost: 2, evs: "0", pokemon: ["Hydrapple","Mega Chesnaught"] },
  { spe: 128, boost: 0, evs: "32+", pokemon: ["Banette","Chimecho","Emboar","Mega Chimecho","Orthworm","Pelipper","Scizor","Umbreon","Vaporeon"] },
  { spe: 128, boost: 0, evs: "0-", pokemon: ["Meowscarada","Noivern"] },
  { spe: 128, boost: 0, evs: "0", pokemon: ["Infernape"] },
  { spe: 127, boost: 1, evs: "0-", pokemon: ["Absol","Mega Heracross"] },
  { spe: 127, boost: 1, evs: "0", pokemon: ["Scizor"] },
  { spe: 127, boost: 1, evs: "0-", pokemon: ["Armarouge"] },
  { spe: 127, boost: 1, evs: "0-", pokemon: ["Florges","Garbodor","Klefki","Mega Banette","Mega Emboar","Mega Scizor","Mega Scovillain","Scovillain"] },
  { spe: 127, boost: 1, evs: "0", pokemon: ["Banette","Chimecho","Emboar","Mega Chimecho","Orthworm","Pelipper","Umbreon","Vaporeon"] },
  { spe: 127, boost: 1, evs: "32", pokemon: ["Mega Crabominable"] },
  { spe: 127, boost: 0, evs: "32", pokemon: ["Armarouge","Mega Heracross","Mega Scizor"] },
  { spe: 127, boost: 0, evs: "32+", pokemon: ["Chesnaught"] },
  { spe: 127, boost: 0, evs: "0-", pokemon: ["Greninja"] },
  { spe: 127, boost: 0, evs: "32", pokemon: ["Absol","Florges","Garbodor","Klefki","Mega Banette","Mega Emboar","Mega Scovillain","Scovillain"] },
  { spe: 126, boost: 2, evs: "0-", pokemon: ["Audino","Azumarill","Beartic","Kingambit","Mega Aggron","Mega Audino","Sableye","Sinistcha"] },
  { spe: 126, boost: 2, evs: "0", pokemon: ["Crabominable"] },
  { spe: 126, boost: 1, evs: "0", pokemon: ["Chesnaught"] },
  { spe: 126, boost: 0, evs: "0-", pokemon: ["Mega Starmie","Sneasler","Mega Pidgeot","Alakazam","Mega Froslass"] },
  { spe: 125, boost: 0, evs: "0", pokemon: ["Espathra","Zoroark","Lopunny","Manectric","Mega Pinsir","Mega Sharpedo"] },
  { spe: 124, boost: 2, evs: "0", pokemon: ["Araquanid"] },
  { spe: 124, boost: 0, evs: "32+", pokemon: ["Tyranitar"] },
  { spe: 124, boost: 0, evs: "0-", pokemon: ["Hawlucha","Mega Hawlucha"] },
  { spe: 124, boost: 0, evs: "0", pokemon: ["Delphox","Meowstic"] },
  { spe: 124, boost: 0, evs: "32", pokemon: ["Slurpuff","Tsareena"] },
  { spe: 123, boost: 1, evs: "0-", pokemon: ["Slurpuff","Tsareena"] },
  { spe: 123, boost: 1, evs: "32", pokemon: ["Cofagrigus","Galarian Slowbro","Galarian Slowking","Mega Abomasnow","Mega Slowbro","Mega Steelix","Reuniclus","Slowbro","Slowking","Snorlax"] },
  { spe: 123, boost: 0, evs: "32", pokemon: ["Mega Tyranitar","Tyrantrum"] },
  { spe: 123, boost: 0, evs: "32+", pokemon: ["Abomasnow","Aegislash","Clefable","Empoleon","Hisuian Decidueye","Hisuian Goodra","Incineroar","Primarina","Sylveon"] },
  { spe: 123, boost: 0, evs: "0", pokemon: ["Mega Excadrill"] },
  { spe: 123, boost: 0, evs: "0-", pokemon: ["Salazzle"] },
  { spe: 123, boost: 0, evs: "32", pokemon: ["Sandaconda"] },
  { spe: 122, boost: 0, evs: "32", pokemon: ["Skarmory","Victreebel"] },
  { spe: 122, boost: 0, evs: "32", pokemon: ["Flapple","Decidueye","Mega Clefable","Mega Victreebel","Mr. Rime","Politoed","Polteageist"] },
  { spe: 122, boost: 0, evs: "0", pokemon: ["Garchomp","Mega Floette"] },
  { spe: 122, boost: 0, evs: "0-", pokemon: ["Whimsicott"] },
  { spe: 121, boost: 1, evs: "0-", pokemon: ["Mega Tyranitar","Tyrantrum","Flapple"] },
  { spe: 121, boost: 1, evs: "0-", pokemon: ["Skarmory","Victreebel"] },
  { spe: 121, boost: 1, evs: "0-", pokemon: ["Sandaconda","Decidueye","Mega Clefable","Mega Victreebel","Mr. Rime","Politoed","Polteageist"] },
  { spe: 121, boost: 1, evs: "0", pokemon: ["Tyranitar"] },
  { spe: 121, boost: 1, evs: "32", pokemon: ["Hatterene"] },
  { spe: 121, boost: 0, evs: "32+", pokemon: ["Aurorus","Pangoro"] },
  { spe: 121, boost: 0, evs: "0", pokemon: ["Mega Glimmora","Pidgeot"] },
  { spe: 121, boost: 0, evs: "0-", pokemon: ["Starmie","Mega Absol","Mega Houndoom"] },
  { spe: 121, boost: 0, evs: "32", pokemon: ["Gourgeist-Large"] },
  { spe: 120, boost: 2, evs: "0", pokemon: ["Rhyperior"] },
  { spe: 120, boost: 2, evs: "0-", pokemon: ["Hippowdon"] },
  { spe: 120, boost: 2, evs: "0", pokemon: ["Forretress"] },
  { spe: 120, boost: 1, evs: "0", pokemon: ["Aegislash"] },
  { spe: 120, boost: 1, evs: "0-", pokemon: ["Gourgeist-Large"] },
  { spe: 120, boost: 1, evs: "0", pokemon: ["Abomasnow","Clefable","Empoleon","Hisuian Decidueye","Hisuian Goodra","Incineroar","Primarina","Sylveon"] },
  { spe: 120, boost: 0, evs: "0", pokemon: ["Mega Charizard X","Mega Dragonite","Mega Gardevoir","Mega Medicham","Volcarona","Paldean Tauros","Typhlosion","Charizard","Mega Charizard Y","Mega Glalie","Mega Kangaskhan","Ninetales","Palafin"] },
  { spe: 119, boost: 0, evs: "0-", pokemon: ["Serperior"] },
  { spe: 119, boost: 0, evs: "0", pokemon: ["Gourgeist-Small"] },
  { spe: 119, boost: 0, evs: "32", pokemon: ["Corviknight"] },
  { spe: 118, boost: 1, evs: "32+", pokemon: ["Mega Camerupt","Mega Sableye","Torkoal"] },
  { spe: 118, boost: 0, evs: "32+", pokemon: ["Torterra","Trevenant"] },
  { spe: 118, boost: 0, evs: "0-", pokemon: ["Lycanroc-Midday","Mega Lucario"] },
  { spe: 118, boost: 0, evs: "0", pokemon: ["Hydreigon"] },
  { spe: 118, boost: 0, evs: "32", pokemon: ["Skeledirge"] },
  { spe: 117, boost: 1, evs: "0-", pokemon: ["Corviknight"] },
  { spe: 117, boost: 1, evs: "0", pokemon: ["Aurorus","Pangoro"] },
  { spe: 117, boost: 0, evs: "32", pokemon: ["Scizor"] },
  { spe: 117, boost: 0, evs: "32+", pokemon: ["Ampharos","Golurk","Machamp","Mega Golurk"] },
  { spe: 117, boost: 0, evs: "0-", pokemon: ["Mega Gallade","Mega Skarmory","Maushold","Gengar","Lycanroc-Dusk","Hisuian Zoroark","Alolan Raichu","Espeon","Froslass","Raichu","Tauros"] },
  { spe: 117, boost: 0, evs: "0", pokemon: ["Morpeko"] },
  { spe: 117, boost: 0, evs: "32", pokemon: ["Banette","Chimecho","Emboar","Mega Chimecho","Orthworm","Pelipper","Umbreon","Vaporeon"] },
  { spe: 116, boost: 2, evs: "0-", pokemon: ["Mega Ampharos"] },
  { spe: 116, boost: 2, evs: "0-", pokemon: ["Bellibolt","Conkeldurr"] },
  { spe: 116, boost: 2, evs: "0", pokemon: ["Hisuian Avalugg"] },
  { spe: 116, boost: 0, evs: "32+", pokemon: ["Gourgeist-Super"] },
  { spe: 116, boost: 0, evs: "0-", pokemon: ["Heliolisk","Alolan Ninetales"] },
  { spe: 116, boost: 0, evs: "0", pokemon: ["Mimikyu"] },
  { spe: 116, boost: 0, evs: "32", pokemon: ["Chesnaught"] },
  { spe: 115, boost: 1, evs: "0-", pokemon: ["Skeledirge"] },
  { spe: 115, boost: 0, evs: "0", pokemon: ["Gliscor","Hisuian Typhlosion","Arcanine","Houndoom","Sharpedo"] },
  { spe: 115, boost: 0, evs: "0-", pokemon: ["Infernape"] },
  { spe: 114, boost: 2, evs: "0-", pokemon: ["Hydrapple","Mega Chesnaught"] },
  { spe: 114, boost: 1, evs: "0-", pokemon: ["Scizor"] },
  { spe: 114, boost: 1, evs: "0", pokemon: ["Torterra"] },
  { spe: 114, boost: 1, evs: "0-", pokemon: ["Banette","Chimecho","Emboar","Mega Chimecho","Orthworm","Pelipper","Umbreon","Vaporeon"] },
  { spe: 114, boost: 1, evs: "0", pokemon: ["Trevenant"] },
  { spe: 114, boost: 0, evs: "0", pokemon: ["Tinkaton"] },
  { spe: 113, boost: 0, evs: "32", pokemon: ["Tyranitar"] },
  { spe: 112, boost: 2, evs: "0-", pokemon: ["Crabominable"] },
  { spe: 112, boost: 2, evs: "0", pokemon: ["Drampa","Mega Drampa"] },
  { spe: 112, boost: 1, evs: "0-", pokemon: ["Chesnaught"] },
  { spe: 112, boost: 1, evs: "0", pokemon: ["Ampharos","Golurk","Machamp","Mega Golurk"] },
  { spe: 112, boost: 0, evs: "32", pokemon: ["Aegislash"] },
  { spe: 112, boost: 0, evs: "32+", pokemon: ["Audino","Azumarill","Beartic","Kingambit","Mega Aggron","Mega Audino","Sableye","Sinistcha"] },
  { spe: 112, boost: 0, evs: "0-", pokemon: ["Espathra","Zoroark","Lopunny","Manectric","Mega Pinsir","Mega Sharpedo"] },
  { spe: 112, boost: 0, evs: "0", pokemon: ["Krookodile","Mega Garchomp"] },
  { spe: 112, boost: 0, evs: "32", pokemon: ["Abomasnow","Clefable","Empoleon","Hisuian Decidueye","Hisuian Goodra","Incineroar","Primarina","Sylveon"] },
  { spe: 111, boost: 1, evs: "0", pokemon: ["Gourgeist-Super"] },
  { spe: 111, boost: 0, evs: "0-", pokemon: ["Delphox","Meowstic"] },
  { spe: 110, boost: 2, evs: "0-", pokemon: ["Araquanid"] },
  { spe: 110, boost: 2, evs: "0", pokemon: ["Garganacl","Mudsdale","Toxapex"] },
  { spe: 110, boost: 0, evs: "0", pokemon: ["Lucario","Hisuian Arcanine","Kangaskhan","Mega Chandelure","Pikachu","Roserade"] },
  { spe: 110, boost: 0, evs: "0-", pokemon: ["Mega Excadrill"] },
  { spe: 110, boost: 0, evs: "32", pokemon: ["Aurorus","Pangoro"] },
  { spe: 109, boost: 0, evs: "0-", pokemon: ["Garchomp","Mega Floette"] },
  { spe: 108, boost: 2, evs: "0-", pokemon: ["Rhyperior"] },
  { spe: 108, boost: 2, evs: "0-", pokemon: ["Forretress"] },
  { spe: 108, boost: 1, evs: "0-", pokemon: ["Aegislash"] },
  { spe: 108, boost: 1, evs: "0-", pokemon: ["Tyranitar","Abomasnow","Clefable","Empoleon","Hisuian Decidueye","Hisuian Goodra","Incineroar","Primarina","Sylveon"] },
  { spe: 108, boost: 1, evs: "32", pokemon: ["Mega Camerupt","Mega Sableye","Torkoal"] },
  { spe: 108, boost: 0, evs: "32", pokemon: ["Torterra"] },
  { spe: 108, boost: 0, evs: "32+", pokemon: ["Hippowdon"] },
  { spe: 108, boost: 0, evs: "0-", pokemon: ["Mega Glimmora","Mega Charizard X","Mega Dragonite","Mega Gardevoir","Mega Medicham","Volcarona","Paldean Tauros","Typhlosion","Pidgeot","Charizard","Mega Charizard Y","Mega Glalie","Mega Kangaskhan","Ninetales","Palafin"] },
  { spe: 108, boost: 0, evs: "0", pokemon: ["Excadrill"] },
  { spe: 108, boost: 0, evs: "32", pokemon: ["Trevenant"] },
  { spe: 107, boost: 0, evs: "0-", pokemon: ["Gourgeist-Small"] },
  { spe: 107, boost: 0, evs: "32", pokemon: ["Ampharos","Golurk","Machamp","Mega Golurk"] },
  { spe: 106, boost: 2, evs: "0", pokemon: ["Mega Crabominable"] },
  { spe: 106, boost: 0, evs: "0", pokemon: ["Rotom-Wash","Glimmora"] },
  { spe: 106, boost: 0, evs: "32+", pokemon: ["Bellibolt","Conkeldurr","Mega Ampharos"] },
  { spe: 106, boost: 0, evs: "0-", pokemon: ["Hydreigon"] },
  { spe: 106, boost: 0, evs: "32", pokemon: ["Gourgeist-Super"] },
  { spe: 105, boost: 1, evs: "0-", pokemon: ["Aurorus","Pangoro"] },
  { spe: 105, boost: 1, evs: "0", pokemon: ["Audino","Azumarill","Beartic","Kingambit","Mega Aggron","Mega Audino","Sableye","Sinistcha"] },
  { spe: 105, boost: 0, evs: "0", pokemon: ["Archaludon","Ceruledge","Heracross","Hisuian Samurott","Kleavor","Kommo-o","Pinsir","Quaquaval"] },
  { spe: 105, boost: 0, evs: "32+", pokemon: ["Hydrapple","Mega Chesnaught"] },
  { spe: 105, boost: 0, evs: "0-", pokemon: ["Morpeko"] },
  { spe: 104, boost: 2, evs: "0-", pokemon: ["Hisuian Avalugg"] },
  { spe: 104, boost: 0, evs: "0", pokemon: ["Gourgeist"] },
  { spe: 104, boost: 0, evs: "32+", pokemon: ["Crabominable"] },
  { spe: 104, boost: 0, evs: "0-", pokemon: ["Mimikyu"] },
  { spe: 103, boost: 0, evs: "32+", pokemon: ["Araquanid"] },
  { spe: 103, boost: 0, evs: "0-", pokemon: ["Gliscor","Hisuian Typhlosion","Arcanine","Houndoom","Sharpedo"] },
  { spe: 102, boost: 1, evs: "0-", pokemon: ["Torterra"] },
  { spe: 102, boost: 1, evs: "0-", pokemon: ["Trevenant"] },
  { spe: 102, boost: 0, evs: "0-", pokemon: ["Tinkaton"] },
  { spe: 102, boost: 0, evs: "32", pokemon: ["Audino","Azumarill","Beartic","Kingambit","Mega Aggron","Mega Audino","Sableye","Sinistcha"] },
  { spe: 101, boost: 0, evs: "0", pokemon: ["Gyarados","Mega Gyarados","Milotic"] },
  { spe: 101, boost: 0, evs: "32+", pokemon: ["Forretress","Rhyperior"] },
  { spe: 100, boost: 2, evs: "0-", pokemon: ["Drampa","Mega Drampa"] },
  { spe: 100, boost: 2, evs: "0", pokemon: ["Cofagrigus","Galarian Slowbro","Galarian Slowking","Mega Abomasnow","Mega Slowbro","Mega Steelix","Reuniclus","Slowbro","Slowking","Snorlax"] },
  { spe: 100, boost: 1, evs: "0-", pokemon: ["Ampharos","Golurk","Machamp","Mega Golurk"] },
  { spe: 100, boost: 1, evs: "0", pokemon: ["Hippowdon"] },
  { spe: 100, boost: 0, evs: "0", pokemon: ["Chandelure","Dragonite","Gallade","Gardevoir","Glalie","Goodra","Mamoswine","Medicham","Mega Altaria","Mega Meganium","Mega Venusaur","Meganium","Venusaur"] },
  { spe: 100, boost: 0, evs: "0-", pokemon: ["Krookodile","Mega Garchomp"] },
  { spe:  99, boost: 1, evs: "0-", pokemon: ["Gourgeist-Super"] },
  { spe:  99, boost: 0, evs: "0", pokemon: ["Vanilluxe"] },
  { spe:  99, boost: 0, evs: "32+", pokemon: ["Hisuian Avalugg"] },
  { spe:  99, boost: 0, evs: "0-", pokemon: ["Lucario","Hisuian Arcanine","Kangaskhan","Mega Chandelure","Pikachu","Roserade"] },
  { spe:  99, boost: 0, evs: "32", pokemon: ["Hippowdon"] },
  { spe:  98, boost: 2, evs: "0-", pokemon: ["Garganacl","Mudsdale","Toxapex"] },
  { spe:  98, boost: 2, evs: "0", pokemon: ["Hatterene"] },
  { spe:  98, boost: 0, evs: "0", pokemon: ["Basculegion","Blastoise","Diggersby","Feraligatr","Mega Blastoise","Mega Feraligatr"] },
  { spe:  97, boost: 1, evs: "0", pokemon: ["Mega Ampharos"] },
  { spe:  97, boost: 1, evs: "0", pokemon: ["Bellibolt","Conkeldurr"] },
  { spe:  97, boost: 0, evs: "32", pokemon: ["Mega Ampharos"] },
  { spe:  97, boost: 0, evs: "0-", pokemon: ["Excadrill"] },
  { spe:  97, boost: 0, evs: "32", pokemon: ["Bellibolt","Conkeldurr"] },
  { spe:  96, boost: 1, evs: "0", pokemon: ["Hydrapple","Mega Chesnaught"] },
  { spe:  96, boost: 0, evs: "32+", pokemon: ["Drampa","Mega Drampa"] },
  { spe:  96, boost: 0, evs: "32", pokemon: ["Hydrapple","Mega Chesnaught"] },
  { spe:  95, boost: 0, evs: "0", pokemon: ["Absol","Armarouge","Florges","Garbodor","Klefki","Mega Banette","Mega Emboar","Mega Heracross","Mega Scizor","Mega Scovillain","Scovillain"] },
  { spe:  95, boost: 0, evs: "32+", pokemon: ["Garganacl","Mudsdale","Toxapex"] },
  { spe:  95, boost: 0, evs: "0-", pokemon: ["Glimmora","Rotom-Wash"] },
  { spe:  95, boost: 0, evs: "32", pokemon: ["Crabominable"] },
  { spe:  94, boost: 2, evs: "0-", pokemon: ["Mega Crabominable"] },
  { spe:  94, boost: 1, evs: "0-", pokemon: ["Audino","Azumarill","Beartic","Kingambit","Mega Aggron","Mega Audino","Sableye","Sinistcha"] },
  { spe:  94, boost: 1, evs: "0", pokemon: ["Crabominable"] },
  { spe:  94, boost: 0, evs: "0-", pokemon: ["Ceruledge","Kommo-o","Quaquaval","Heracross","Hisuian Samurott","Archaludon","Kleavor","Pinsir"] },
  { spe:  94, boost: 0, evs: "32", pokemon: ["Araquanid"] },
  { spe:  93, boost: 1, evs: "0", pokemon: ["Araquanid"] },
  { spe:  93, boost: 0, evs: "32+", pokemon: ["Mega Crabominable"] },
  { spe:  93, boost: 0, evs: "0-", pokemon: ["Gourgeist"] },
  { spe:  92, boost: 0, evs: "0", pokemon: ["Slurpuff","Tsareena"] },
  { spe:  92, boost: 0, evs: "32", pokemon: ["Rhyperior"] },
  { spe:  92, boost: 0, evs: "32", pokemon: ["Forretress"] },
  { spe:  91, boost: 0, evs: "0", pokemon: ["Mega Tyranitar","Sandaconda","Tyrantrum"] },
  { spe:  90, boost: 2, evs: "0-", pokemon: ["Cofagrigus","Galarian Slowbro","Galarian Slowking","Mega Abomasnow","Mega Slowbro","Mega Steelix","Reuniclus","Slowbro","Slowking","Snorlax"] },
  { spe:  90, boost: 1, evs: "0", pokemon: ["Rhyperior"] },
  { spe:  90, boost: 1, evs: "0-", pokemon: ["Hippowdon"] },
  { spe:  90, boost: 1, evs: "0", pokemon: ["Forretress"] },
  { spe:  90, boost: 0, evs: "0", pokemon: ["Decidueye","Flapple","Mega Clefable","Mega Victreebel","Mr. Rime","Politoed","Polteageist","Skarmory","Victreebel"] },
  { spe:  90, boost: 0, evs: "32+", pokemon: ["Cofagrigus","Galarian Slowbro","Galarian Slowking","Mega Abomasnow","Mega Slowbro","Mega Steelix","Reuniclus","Slowbro","Slowking","Snorlax"] },
  { spe:  90, boost: 0, evs: "0-", pokemon: ["Gyarados","Mega Gyarados","Dragonite","Gallade","Gardevoir","Mega Altaria","Venusaur","Mamoswine","Medicham","Milotic","Chandelure","Glalie","Goodra","Mega Meganium","Mega Venusaur","Meganium"] },
  { spe:  90, boost: 0, evs: "32", pokemon: ["Hisuian Avalugg"] },
  { spe:  89, boost: 0, evs: "0", pokemon: ["Gourgeist-Large"] },
  { spe:  89, boost: 0, evs: "32+", pokemon: ["Hatterene"] },
  { spe:  89, boost: 0, evs: "0-", pokemon: ["Vanilluxe"] },
  { spe:  88, boost: 2, evs: "0-", pokemon: ["Hatterene"] },
  { spe:  88, boost: 0, evs: "0-", pokemon: ["Basculegion","Blastoise","Diggersby","Feraligatr","Mega Blastoise","Mega Feraligatr"] },
  { spe:  88, boost: 0, evs: "32", pokemon: ["Drampa","Mega Drampa"] },
  { spe:  87, boost: 1, evs: "0-", pokemon: ["Mega Ampharos"] },
  { spe:  87, boost: 1, evs: "0-", pokemon: ["Bellibolt","Conkeldurr"] },
  { spe:  87, boost: 1, evs: "0", pokemon: ["Hisuian Avalugg"] },
  { spe:  87, boost: 0, evs: "0", pokemon: ["Corviknight"] },
  { spe:  87, boost: 0, evs: "32", pokemon: ["Garganacl","Mudsdale","Toxapex"] },
  { spe:  86, boost: 0, evs: "0", pokemon: ["Skeledirge"] },
  { spe:  85, boost: 1, evs: "0-", pokemon: ["Hydrapple","Mega Chesnaught"] },
  { spe:  85, boost: 0, evs: "0", pokemon: ["Banette","Chimecho","Emboar","Mega Chimecho","Orthworm","Pelipper","Scizor","Umbreon","Vaporeon"] },
  { spe:  85, boost: 0, evs: "0-", pokemon: ["Armarouge","Absol","Mega Heracross","Florges","Garbodor","Klefki","Mega Banette","Mega Emboar","Mega Scizor","Mega Scovillain","Scovillain"] },
  { spe:  85, boost: 0, evs: "32", pokemon: ["Mega Crabominable"] },
  { spe:  84, boost: 1, evs: "0-", pokemon: ["Crabominable"] },
  { spe:  84, boost: 1, evs: "0", pokemon: ["Drampa","Mega Drampa"] },
  { spe:  84, boost: 0, evs: "0", pokemon: ["Chesnaught"] },
  { spe:  82, boost: 1, evs: "0-", pokemon: ["Araquanid"] },
  { spe:  82, boost: 1, evs: "0", pokemon: ["Garganacl","Mudsdale","Toxapex"] },
  { spe:  82, boost: 0, evs: "0-", pokemon: ["Slurpuff","Tsareena"] },
  { spe:  82, boost: 0, evs: "32", pokemon: ["Cofagrigus","Galarian Slowbro","Galarian Slowking","Mega Abomasnow","Mega Slowbro","Mega Steelix","Reuniclus","Slowbro","Slowking","Snorlax"] },
  { spe:  81, boost: 1, evs: "0-", pokemon: ["Rhyperior"] },
  { spe:  81, boost: 1, evs: "0-", pokemon: ["Forretress"] },
  { spe:  81, boost: 0, evs: "0", pokemon: ["Tyranitar"] },
  { spe:  81, boost: 0, evs: "0-", pokemon: ["Mega Tyranitar","Tyrantrum","Flapple","Skarmory","Victreebel","Sandaconda","Decidueye","Mega Clefable","Mega Victreebel","Mr. Rime","Politoed","Polteageist"] },
  { spe:  81, boost: 0, evs: "32", pokemon: ["Hatterene"] },
  { spe:  80, boost: 2, evs: "0", pokemon: ["Mega Camerupt","Mega Sableye","Torkoal"] },
  { spe:  80, boost: 0, evs: "0", pokemon: ["Abomasnow","Aegislash","Clefable","Empoleon","Hisuian Decidueye","Hisuian Goodra","Incineroar","Primarina","Sylveon"] },
  { spe:  80, boost: 0, evs: "0-", pokemon: ["Gourgeist-Large"] },
  { spe:  79, boost: 1, evs: "0", pokemon: ["Mega Crabominable"] },
  { spe:  79, boost: 0, evs: "32+", pokemon: ["Mega Camerupt","Mega Sableye","Torkoal"] },
  { spe:  78, boost: 1, evs: "0-", pokemon: ["Hisuian Avalugg"] },
  { spe:  78, boost: 0, evs: "0", pokemon: ["Aurorus","Pangoro"] },
  { spe:  78, boost: 0, evs: "0-", pokemon: ["Corviknight"] },
  { spe:  77, boost: 0, evs: "0-", pokemon: ["Skeledirge"] },
  { spe:  76, boost: 0, evs: "0", pokemon: ["Torterra","Trevenant"] },
  { spe:  76, boost: 0, evs: "0-", pokemon: ["Scizor","Banette","Chimecho","Emboar","Mega Chimecho","Orthworm","Pelipper","Umbreon","Vaporeon"] },
  { spe:  75, boost: 1, evs: "0-", pokemon: ["Drampa","Mega Drampa"] },
  { spe:  75, boost: 1, evs: "0", pokemon: ["Cofagrigus","Galarian Slowbro","Galarian Slowking","Mega Abomasnow","Mega Slowbro","Mega Steelix","Reuniclus","Slowbro","Slowking","Snorlax"] },
  { spe:  75, boost: 0, evs: "0", pokemon: ["Ampharos","Golurk","Machamp","Mega Golurk"] },
  { spe:  75, boost: 0, evs: "0-", pokemon: ["Chesnaught"] },
  { spe:  74, boost: 0, evs: "0", pokemon: ["Gourgeist-Super"] },
  { spe:  73, boost: 1, evs: "0-", pokemon: ["Garganacl","Mudsdale","Toxapex"] },
  { spe:  73, boost: 1, evs: "0", pokemon: ["Hatterene"] },
  { spe:  72, boost: 2, evs: "0-", pokemon: ["Mega Camerupt","Mega Sableye","Torkoal"] },
  { spe:  72, boost: 0, evs: "0-", pokemon: ["Aegislash","Tyranitar","Abomasnow","Clefable","Empoleon","Hisuian Decidueye","Hisuian Goodra","Incineroar","Primarina","Sylveon"] },
  { spe:  72, boost: 0, evs: "32", pokemon: ["Mega Camerupt","Mega Sableye","Torkoal"] },
  { spe:  70, boost: 1, evs: "0-", pokemon: ["Mega Crabominable"] },
  { spe:  70, boost: 0, evs: "0", pokemon: ["Audino","Azumarill","Beartic","Kingambit","Mega Aggron","Mega Audino","Sableye","Sinistcha"] },
  { spe:  70, boost: 0, evs: "0-", pokemon: ["Aurorus","Pangoro"] },
  { spe:  68, boost: 0, evs: "0-", pokemon: ["Torterra","Trevenant"] },
  { spe:  67, boost: 1, evs: "0-", pokemon: ["Cofagrigus","Galarian Slowbro","Galarian Slowking","Mega Abomasnow","Mega Slowbro","Mega Steelix","Reuniclus","Slowbro","Slowking","Snorlax"] },
  { spe:  67, boost: 0, evs: "0", pokemon: ["Hippowdon"] },
  { spe:  67, boost: 0, evs: "0-", pokemon: ["Ampharos","Golurk","Machamp","Mega Golurk"] },
  { spe:  66, boost: 1, evs: "0-", pokemon: ["Hatterene"] },
  { spe:  66, boost: 0, evs: "0-", pokemon: ["Gourgeist-Super"] },
  { spe:  65, boost: 0, evs: "0", pokemon: ["Bellibolt","Conkeldurr","Mega Ampharos"] },
  { spe:  64, boost: 0, evs: "0", pokemon: ["Hydrapple","Mega Chesnaught"] },
  { spe:  63, boost: 0, evs: "0-", pokemon: ["Audino","Azumarill","Beartic","Kingambit","Mega Aggron","Mega Audino","Sableye","Sinistcha"] },
  { spe:  63, boost: 0, evs: "0", pokemon: ["Crabominable"] },
  { spe:  62, boost: 0, evs: "0", pokemon: ["Araquanid"] },
  { spe:  60, boost: 1, evs: "0", pokemon: ["Mega Camerupt","Mega Sableye","Torkoal"] },
  { spe:  60, boost: 0, evs: "0-", pokemon: ["Hippowdon"] },
  { spe:  60, boost: 0, evs: "0", pokemon: ["Forretress","Rhyperior"] },
  { spe:  58, boost: 0, evs: "0-", pokemon: ["Bellibolt","Conkeldurr","Mega Ampharos"] },
  { spe:  58, boost: 0, evs: "0", pokemon: ["Hisuian Avalugg"] },
  { spe:  57, boost: 0, evs: "0-", pokemon: ["Hydrapple","Mega Chesnaught"] },
  { spe:  56, boost: 0, evs: "0-", pokemon: ["Crabominable"] },
  { spe:  56, boost: 0, evs: "0", pokemon: ["Drampa","Mega Drampa"] },
  { spe:  55, boost: 0, evs: "0-", pokemon: ["Araquanid"] },
  { spe:  55, boost: 0, evs: "0", pokemon: ["Garganacl","Mudsdale","Toxapex"] },
  { spe:  54, boost: 1, evs: "0-", pokemon: ["Mega Camerupt","Mega Sableye","Torkoal"] },
  { spe:  54, boost: 0, evs: "0-", pokemon: ["Forretress","Rhyperior"] },
  { spe:  53, boost: 0, evs: "0", pokemon: ["Mega Crabominable"] },
  { spe:  52, boost: 0, evs: "0-", pokemon: ["Hisuian Avalugg"] },
  { spe:  50, boost: 0, evs: "0-", pokemon: ["Drampa","Mega Drampa"] },
  { spe:  50, boost: 0, evs: "0", pokemon: ["Cofagrigus","Galarian Slowbro","Galarian Slowking","Mega Abomasnow","Mega Slowbro","Mega Steelix","Reuniclus","Slowbro","Slowking","Snorlax"] },
  { spe:  49, boost: 0, evs: "0-", pokemon: ["Garganacl","Mudsdale","Toxapex"] },
  { spe:  49, boost: 0, evs: "0", pokemon: ["Hatterene"] },
  { spe:  47, boost: 0, evs: "0-", pokemon: ["Mega Crabominable"] },
  { spe:  45, boost: 0, evs: "0-", pokemon: ["Cofagrigus","Galarian Slowbro","Galarian Slowking","Mega Abomasnow","Mega Slowbro","Mega Steelix","Reuniclus","Slowbro","Slowking","Snorlax"] },
  { spe:  44, boost: 0, evs: "0-", pokemon: ["Hatterene"] },
  { spe:  40, boost: 0, evs: "0", pokemon: ["Mega Camerupt","Mega Sableye","Torkoal"] },
  { spe:  36, boost: 0, evs: "0-", pokemon: ["Mega Camerupt","Mega Sableye","Torkoal"] },
];

// Build unique pokemon list
const ALL_POKEMON = [...new Set(SPEED_DATA.flatMap(d => d.pokemon))].sort();

// Lookup: pokemon -> all tiers
function getTiersForPokemon(name) {
  return SPEED_DATA.filter(d => d.pokemon.includes(name)).sort((a, b) => b.spe - a.spe);
}

// Get speed for specific pokemon + boost + evs combo
function getSpeed(name, boost, evs) {
  const tier = SPEED_DATA.find(d =>
    d.pokemon.includes(name) &&
    d.boost === parseInt(boost) &&
    d.evs === evs
  );
  return tier ? tier.spe : null;
}

// Pokemon sprite URL (uses PokeAPI sprites via Smogon convention)
function getSpriteUrl(name) {
  // Convert name to Smogon sprite key
  const key = name
    .toLowerCase()
    .replace(/^mega\s+/,  '')
    .replace(/\s+/g, '-')
    .replace(/['.]/g, '')
    .replace(/^alolan\s*/,  '')
    .replace(/^galarian\s*/, '')
    .replace(/^hisuian\s*/, '')
    .replace(/^paldean\s*/, '');
  return `https://play.pokemonshowdown.com/sprites/ani/${key}.gif`;
}
